source 'https://rubygems.org'
ruby '2.1.2'
gem 'rails', '4.2.0'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem "activeadmin", git: "https://github.com/gregbell/active_admin"
gem 'kaminari', '0.16.3'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'thin'
gem 'rails-rake-pg'
gem 'therubyracer'
gem 'bootstrap-sass'
gem 'devise'
gem 'pundit'
gem 'high_voltage'
gem 'simple_form', '~> 3.1.0'

group :development, :test do
  gem 'gist'
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-clipboard'
  gem 'pry-docmore'
  gem 'pry-git'
  gem 'pry-remote'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  gem 'guard'
  gem 'guard-bundler'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'rb-fchange', :require=>false
  gem 'rb-fsevent', :require=>false
  gem 'rb-inotify', :require=>false
  gem 'binding_of_caller', '~> 0.7.3.pre1'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-rails'
  gem 'rails-erd'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'better_errors'
end
group :production do
  gem 'rails_12factor'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end
