#!/home/sdownie/.rubies/ruby-2.1.3/bin/ruby
###
# TommyTalker web app
# this file loads up the category_phrases table
# using phrase keys so that all 27 languages
# get populated into the category_phrases table
###
require 'yaml'
require 'pg'
require 'pry'
rb_frequent=[
 'assoonaspossible', 'bequiet', 'callme', 'certainly', 'cheers',
 'dontdothat', 'dontworry', 'everyoneknowsit', 'everyweek', 'excellent',
 'fuckthat', 'goodafternoon', 'goodluck', 'goodmorning', 'great',
 'heather', 'howisshe', 'howmany', 'hurry', 'iagree',
 'iforget', 'igiveup', 'iknow', 'ilikeit', 'illpay',
 'iloveyou', 'imgood', 'ithinkso', 'itsok', 'judy',
 'julianne', 'letseat', 'letsgo', 'maybe', 'noo',
 'noproblem', 'nothankyou', 'notyet', 'now', 'ofcourse',
 'ok', 'openthedoor', 'please', 'really', 'righthere',
 'rightthere', 'sarah', 'seeyoulater'
]
rb_q_and_a = ['andyou','anythingelse','arethereanyconcerts','aretheycomingthisevening',
'aretheythesame','areyouafraid','areyouallergictoanything','areyouamerican',
'areyoubusy','areyoucomfortable','areyoucomingthisevening','areyoufreetonight',
'areyougoingtoattendtheirwedding','areyougoingtohelpher','areyougoingtotakeaplane',
'areyouherealone','areyouhungry','areyoumarried','areyouok','areyourchildrenwithyou',
'areyouready','areyousick','areyousure','areyouwaitingforsomeone','areyouworkingtoday',
'areyouworkingtomorrow','atwhattime','atwhattimedidithappen','caniaccesstheinternethere','caniborrowsomemoney',
'canibringmyfriend','canihaveaglassofwaterplease','canihaveareceiptplease','canihavethebillplease','canihelpyou',
'canimakeanappointmentfornextwednesday','caniseeyourpassportplease','canitakeamessage','canitbecheaper','canitryiton',
'caniuseyourphone','canwehaveamenuplease','canwehavesomemorebreadplease','canwesitoverthere','canyoucallbacklater',
'canyoucarrythisforme','canyoudomeafavor','canyoufixthis','canyougivemeanexample','canyouhelpme',
'canyouholdthisforme','canyoupleasehelpme','canyoupleasesaythatagain','canyourecommendagoodrestaurant','canyourepeatthatplease',
'canyoushowme','canyouspeaklouderplease','canyouswim','canyouthrowthatawayforme','canyoutranslatethisforme',
'diditsnowyesterday','didyoucomewithyourfamily','didyougetmyemail','didyourwifelikecalifornia','didyousendmeflowers',
'didyoutakeyourmedicine','doesanyoneherespeakenglish','doesheliketheschool','doesitoftensnowinthewinterinmassachusetts','doesthisroadgotonewyork',
'doyouacceptusdollars','doyoubelievethat','doyoufeelbetter','doyougotofloridaoften','doyouhaveaboyfriend',
'doyouhaveagirlfriend','doyouhaveanappointment','doyouhaveanotherone','doyouhaveanychildren','doyouhaveanycoffee',
'doyouhaveanymoney','doyouhaveanythingcheaper','doyouhaveanyvacancies','doyouhaveapencil','doyouhaveaproblem',
'doyouhaveaswimmingpool','doyouhaveenoughmoney','doyouhavethenumberforataxi','doyouhavethisinsizeeleven','doyouhearthat',
'doyouknowher','doyouknowhowmuchitcosts','doyouknowhowtocook','doyouknowhowtogettothemarriotthotel','doyouknowwhatthismeans',
'doyouknowwhatthissays','doyouknowwhereicangetataxi','doyouknowwheremyglassesare','doyouknowwheresheis','doyouknowwheretheresastorethatsellstow',
'doyoulikeithere','doyoulikethebook','doyouliketowatchtv','doyoulikeyourboss','doyoulikeyourcoworkers',
'doyouneedanything','doyouneedanythingelse','doyouplayanysports','doyouplaybasketball','doyousellbatteries',
'doyousellmedicine','doyousmoke','doyouspeakenglish','doyoustudyenglish','doyoutakecreditcards',
'doyouthinkitllraintoday','doyouthinkitsgoingtoraintoday','doyouthinkitspossible','doyouthinkyoullbebackbyeleventhirty','doyouunderstand',
'doyouwantmetocomeandpickyouup','doyouwanttocomewithme','doyouwanttogotothemovies','doyouwanttogowithme','excusemewhatdidyousay',
'forhowmanynights','hasyourbrotherbeentocalifornia','havetheymetheryet','haveyouarrived','haveyoubeentoboston',
'haveyoubeenwaitinglong','haveyoudonethisbefore','haveyoueatenatthatrestaurant','haveyoueatenyet','haveyoueverhadpotatosoup',
'haveyoufinishedstudying','haveyouseenthismovie','help','howaboutsaturday','howareyou',
'howareyoupaying','howareyourparents','howdoesittaste','howdoigetthere','howdoigettodanielstreet',
'howdoigettotheamericanembassy','howdoiusethis','howdoyouknow','howdoyoupronouncethat','howdoyousayitinenglish',
'howdoyouspellit','howdoyouspellthewordseattle','howfarisit','howfarisittochicago','howisshe',
'howlongareyougoingtostay','howlongareyougoingtostayincalifornia','howlongdoesittakebycar','howlongdoesittaketogettogeorgia','howlonghaveyoubeenhere',
'howlonghaveyouworkedhere','howlongisit','howlongistheflight','howlongwillittake','howlongwillyoubestaying',
'howmany','howmanychildrendoyouhave','howmanyhoursaweekdoyouwork','howmanylanguagesdoyouspeak','howmanymilesisittopennsylvania',
'howmanypeople','howmanypeoplearethereinnewyork','howmanypeopledoyouhaveinyourfamily','howmuchalltogether','howmucharetheseearrings',
'howmuchdoesitcostperday','howmuchdoesthiscost','howmuchdoioweyou','howmuchisit','howmuchisittogotomiami',
'howmuchisthat','howmuchisthis','howmuchmoneydoyouhave','howmuchmoneydoyoumake','howmuchwillitcost',
'howmuchwouldyoulike','howoldareyou','howsbusiness','howstheweather','howsworkgoing',
'howtallareyou','howwasthemovie','howwasthetrip','isanyoneelsecoming','iseverythingok',
'isitclose','isitcoldoutside','isitfarfromhere','isithot','isitnearby',
'isitpossible','isitraining','isitready','isitsupposedtoraintomorrow','isjohnhere',
'isjohnthereplease','ismr.smithanamerican','isntit','isthatenough','isthatok',
'isthebankfar','isthereairconditioningintheroom','isthereamovietheaternearby','isthereanenglishspeakingguide','isthereanightclubintown',
'isthereanymailforme','isthereanythingcheaper','istherearestaurantinthehotel','isthereastorenearhere','isthisasafearea',
'isthismr.smith','isthispenyours','isthisthebustony','isthisyourbook','isyourfatherhome',
'isyourhouselikethisone','isyourhusbandalsofromboston','isyoursonhere','onewayorroundtrip','werethereanyproblems',
'wereyouatthelibrarylastnight','whatareyoudoing','whatareyougoingtodotonight','whatareyougoingtohave','whatareyourhobbies',
'whatareyouthinkingabout','whatareyoutwotalkingabout','whatcanidoforyou','whatcoloristhatcar','whatdayaretheycomingover',
'whatdayoftheweekisit','whatdidyoudolastnight','whatdidyoudoyesterday','whatdidyouthink','whatdoeshedoforwork',
'whatdoesthismean','whatdoesthissay','whatdoesthiswordmean','whatdoesyourfatherdoforwork','whatdopeopleusuallydointhesummerinlosangeles',
'whatdotheystudy','whatdoyoudoforwork','whatdoyouhave','whatdoyourecommend','whatdoyourparentsdoforwork',
'whatdoyoustudy','whatdoyouthink','whatdoyouthinkoftheseshoes','whatdoyouwant','whatdoyouwanttobuy',
'whatdoyouwanttodo','whathappened','whatisit','whatisthat','whatistheareacode',
'whatistodaysdate','whatkindofmusicdoyoulike','whatschooldidyougoto','whatshouldiwear','whatsinit',
'whatsize','whatstheaddress','whatsthechargepernight','whatsthedate','whatstheexchangerate',
'whatstheexchangeratefordollars','whatsthematter','whatsthenameofthecompanyyouworkfor','whatsthephonenumber','whatstheroomrate',
'whatsthetemperature','whatsthis','whatstodaysdate','whatsup','whatswrong',
'whatsyouraddress','whatsyourfavoritefood','whatsyourfavoritemovie','whatsyourlastname','whatsyourname',
'whatsyourreligion','whattimearetheyarriving','whattimeareyougoingtothebusstation','whattimedidyougetup','whattimedidyougotosleep',
'whattimedidyouwakeup','whattimedoesitstart','whattimedoesthemoviestart','whattimedoesthestoreopen','whattimedoyougotoworkeveryday',
'whattimedoyouthinkyoullarrive','whattimeischeckout','whattimeisit','whatwilltheweatherbeliketomorrow','whatwouldyouliketodrink',
'whatwouldyouliketoeat','whenaretheycoming','whenareyoucomingback','whenareyougoingtopickupyourfriend','whenareyouleaving',
'whenareyoumoving','whendidthishappen','whendidyouarriveinboston','whendoeshearrive','whendoesitarrive',
'whendoesitleave','whendoesthebankopen','whendoesthebusleave','whendoestheplanearrive','whendowearrive',
'whendoyouarriveintheunitedstates','whendoyougetoffwork','whenisthenextbustophiladelphia','whenisyourbirthday','wheniwenttothestoretheydidnthaveanyapples',
'whenwillitbeready','whenwouldyouliketomeet','wherearethetshirts','whereareyou','whereareyoufrom',
'whereareyougoing','whereareyougoingtogo','wherecanibuytickets','wherecaniexchangeusdollars','wherecanifindahospital',
'wherecanimailthis','wherecanirentacar','wheredidithappen','wheredidyougo','wheredidyoulearnenglish',
'wheredidyoulearnit','wheredidyouputit','wheredidyouworkbeforeyouworkedhere','wheredoesithurt','wheredoesyourwifework',
'wheredoyoulive','wheredoyouwanttogo','wheredoyouwork','whereishe','whereishefrom',
'whereisit','whereismainstreet','whereismyshirt','whereisshefrom','whereistheairport',
'whereisthebathroom','whereisthebusstation','whereisthereadoctorwhospeaksenglish','whereisthereanatm','wherestheclosestrestaurant',
'wheresthemailbox','wheresthenearesthospital','wheresthepharmacy','wheresthepostoffice','wherewereyou',
'wherewouldyouliketogo','wherewouldyouliketomeet','whichisbetter','whichisbetterthespaghettiorchickensalad','whichisthebest',
'whichone','whichonedoyouwant','whichoneisbetter','whichoneischeaper','whichoneisthebest',
'whichroadshoulditake','whichschooldoeshegoto','whoarethey','whoisit','whoisthat',
'whosbookisthat','whosentthisletter','whosthatmanoverthere','whotaughtyou','whotaughtyouthat',
'whowasthat','whowasyourteacher','whowon','whowouldyouliketospeakto','whyarentyougoing',
'whyareyoulaughing','whydidyoudothat','whydidyousaythat','whynot','willyoucallmeataxiplease',
'willyouhandmeatowelplease','willyoupassmethesaltplease','willyouputthisinthecarforme','willyouremindme','willyoutakemehome',
'wouldyouaskhimtocallmebackplease','wouldyouaskhimtocomehere','wouldyoulikeaglassofwater','wouldyoulikecoffeeortea','wouldyoulikesomethingtodrink',
'wouldyoulikesomethingtoeat','wouldyoulikesomewater','wouldyoulikesomewine','wouldyouliketobuythis','wouldyouliketogoforawalk',
'wouldyouliketohavedinnerwithme','wouldyouliketorentamovie','wouldyouliketowatchtv','wouldyoulikewaterormilk','wouldyoutakeamessageplease'
]
rb_chat = [
 'afew', 'alittle', 'allday', 'alongtimeago', 'andyou',
 'anythingelse', 'areyouafraid', 'areyoubusy', 'becareful', 'becarefuldriving',
 'bequiet', 'callme', 'canihelpyou', 'canitryiton', 'canyoudomeafavor',
 'canyoufixthis', 'canyouhelpme', 'canyoushowme', 'certainly', 'cheers',
 'comehere', 'dontdothat', 'dontworry', 'everyweek', 'excellent',
 'excuseme', 'forgetit', 'fuckthat', 'givemeacall', 'goodidea',
 'goodluck', 'goodmorning', 'great', 'heather', 'hello',
 'help', 'hereitis', 'howmany', 'howmanypeople', 'howmuchisit',
 'hurry', 'iagree', 'idontcare', 'idontmind', 'ifeelgood',
 'iforget', 'igiveup', 'iknow', 'illpay', 'iloveyou',
 'imok', 'imready', 'imsorry', 'imtired', 'isthatenough',
 'isthatok', 'itshere', 'itsmine', 'itsok', 'iunderstand',
 'letseat', 'letsgo', 'maybe', 'noo', 'noproblem',
 'nothankyou', 'notyet', 'now', 'ofcourse', 'ok',
 'please', 'really', 'sarah', 'seeyoulater', 'stop',
 'tellme', 'thanks', 'thankyou', 'thatsit', 'thatway',
 'thewholeday', 'verygoodthanks', 'whatsup', 'whatswrong', 'whattimeisit',
 'whereishe', 'whereisit', 'whichone', 'whynot', 'yess'
]
rb_food = [
 'alittle', 'anythingelse', 'areyouherealone', 'areyouhungry', 'areyousure',
 'canihaveareceiptplease', 'canihavethebillplease', 'canwehaveamenuplease', 'canwehavesomemorebreadplease', 'canyourepeatthatplease',
 'certainly', 'cheers', 'doyouhaveanycoffee', 'doyouknowhowtocook', 'doyoulikeithere',
 'doyouneedanything', 'doyouneedanythingelse', 'doyouthinkitspossible', 'doyouunderstand', 'everyweek',
 'excellent', 'excuseme', 'excusemewhatdidyousay', 'fillitupplease', 'fuckthat',
 'goodidea', 'great', 'happybirthday', 'haveyoueatenyet', 'haveyoueverhadpotatosoup',
 'heather', 'heresyourorder', 'heresyoursalad', 'hereyouare', 'hesinthekitchen',
 'howaboutsaturday', 'howareyoupaying', 'howdoesittaste', 'howlongwillittake', 'howmuchdoesthiscost',
 'howmuchdoioweyou', 'howmuchisit', 'howmuchisthat', 'howmuchisthis', 'howmuchwouldyoulike',
 'iagree', 'iatealready', 'idlikesomewatertooplease', 'idliketoeatatfifthstreetrestaurant', 'idontcare',
 'idontwantit', 'idontwantthat', 'ifyoulikeiticanbuymore', 'ihaventfinishedeating', 'ihaventhadlunchyet',
 'ilikeit', 'ilikeitalianfood', 'illpay', 'illpayfordinner', 'illtakeit',
 'imfull', 'imhungry', 'imnotsure', 'imok', 'imready',
 'imthirsty', 'inthirtyminutes', 'iseverythingok', 'isithot', 'isntit',
 'isthatenough', 'isthatok', 'istherearestaurantinthehotel', 'istillhaventdecided', 'ithinkitsverygood',
 'ithinkittastesgood', 'ithinkso', 'itsdelicious', 'itshere', 'itsnotveryexpensive',
 'itsok', 'itsreallyhot', 'judy', 'julianne', 'justalittle',
 'letseat', 'letsshare', 'morethanthat', 'mydaughterishere', 'noo',
 'noproblem', 'nothankyou', 'nothingelse', 'now', 'ofcourse',
 'ok', 'onelikethat', 'please', 'pleasesitdown', 'really',
 'righthere', 'rightthere', 'sarah', 'seeyoulater', 'thanks',
 'thanksforeverything', 'thankyou', 'thankyoumiss', 'thankyousir', 'thankyouverymuch',
 'thatsalright', 'thatsenough', 'thatsfair', 'thatsfine', 'thatsgood',
 'thatsgreat', 'thatsit', 'thatsmellsbad', 'thatsnotenough', 'thatsnotfair',
 'thatsnotright', 'thatsright', 'thatstoobad', 'thatstooexpensive', 'thatstoolate',
 'thatstoomany', 'thatstoomuch', 'thatswrong', 'verygoodthanks', 'waiter',
 'waitress', 'wecaneatitalianorchinesefood', 'welikeitverymuch', 'whatdoesthismean', 'whatdoesthissay',
 'whatdoyouthink', 'whatdoyouwant', 'whatisit', 'whatisthat', 'whatsize',
 'whatsthis', 'whattimeisit', 'whatwouldyouliketodrink', 'whatwouldyouliketoeat', 'whenwillitbeready',
 'whenwouldyouliketomeet', 'whereareyou', 'wherestheclosestrestaurant', 'whichisbetter', 'whichisthebest',
 'whichone', 'whichonedoyouwant', 'whichoneisbetter', 'whichoneischeaper', 'whichoneisthebest',
 'willyouhandmeatowelplease', 'willyoupassmethesaltplease', 'wouldyoulikesomethingtodrink', 'wouldyoulikesomethingtoeat', 'wouldyoulikesomewater',
 'wouldyoulikesomewine', 'wouldyouliketohavedinnerwithme', 'wouldyoulikewaterormilk', 'yesreally', 'yess', 'yourewelcome'
]
rb_health=[
 'alittle', 'allday', 'alongtimeago', 'areyouallergictoanything', 'areyoucomfortable',
 'areyouhungry', 'areyouok', 'areyouready', 'areyousick', 'areyousure',
 'assoonaspossible', 'atwhattime', 'becareful', 'bequiet', 'canitbecheaper',
 'canyoudomeafavor', 'canyouhelpme', 'canyouholdthisforme', 'canyoupleasehelpme', 'canyoupleasesaythatagain',
 'canyourepeatthatplease', 'canyoushowme', 'certainly', 'didyoutakeyourmedicine', 'dontdothat',
 'dontworry', 'doyouhaveanappointment', 'doyouhaveanotherone', 'doyouhaveanycoffee', 'doyouknowhowmuchitcosts',
 'doyouknowwheremyglassesare', 'doyouneedanything', 'doyouneedanythingelse', 'doyousellmedicine', 'doyousmoke',
 'excellent', 'excusemewhatdidyousay', 'expirationdate', 'forhowmanynights', 'fuckthat',
 'great', 'haveyoueatenyet', 'healwaysdoesthatforme', 'heather', 'hellbebackintwentyminutes',
 'hesright', 'hesveryannoying', 'howaboutsaturday', 'howdoyoupronouncethat', 'howisshe',
 'howlonghaveyoubeenhere', 'howlongwillittake', 'howlongwillyoubestaying', 'howmany', 'howmuchdoesthiscost',
 'howmuchdoioweyou', 'howmuchisit', 'howmuchisthat', 'howmuchisthis', 'howoldareyou',
 'howsworkgoing', 'howwasthetrip', 'iagree', 'iatealready', 'icamewithmyfamily',
 'icanthearyou', 'icanthearyouclearly', 'idliketogoforawalk', 'idliketogohome', 'idliketomakeaphonecall',
 'idliketousetheinternet', 'idontlikehim', 'idontlikeit', 'idontmind', 'idontthinkso',
 'idontunderstand', 'idontunderstandwhatyoursaying', 'idontwantit', 'idontwantthat', 'ifeelgood',
 'iforget', 'ifyouneedmyhelppleaseletmeknow', 'igotinanaccident', 'ihaveacold', 'ihaveaheadache',
 'ihaventhadlunchyet', 'ihavepaininmyarm', 'iknow', 'ilikeher', 'ilikeit',
 'illberightback', 'illcomebacklater', 'illgiveyouacall', 'illhavethesamething', 'illtakeit',
 'imallergictoseafood', 'imbored', 'imcold', 'imfineandyou', 'imfull',
 'imgoingtobed', 'imgoingtoleave', 'imgood', 'imgoodandyou', 'imhappy',
 'imhot', 'imhungry', 'imnotafraid', 'imnotreadyyet', 'imnotsure',
 'imok', 'imready', 'imsick', 'imthirsty', 'imtired',
 'imverywellthankyou', 'imworriedtoo', 'ineedadoctor', 'ineedsometissues', 'ineedtogonow',
 'ineedtogotobed', 'ineedtogotothebathroom', 'inthirtyminutes', 'ionlywantasnack', 'isitready',
 'isntit', 'isthatenough', 'isthatok', 'isthisasafearea', 'ithinkso',
 'ithurtshere', 'itrustyou', 'itsmine', 'itsok', 'itsreallyhot',
 'iunderstand', 'iunderstandnow', 'ivealreadyseenit', 'iveseenit', 'iwishihadone',
 'judy', 'julianne', 'justalittle', 'justamoment', 'letmecheck',
 'letmethinkaboutit', 'letseat', 'letsgo', 'maybe', 'morethanthat',
 'mystomachhurts', 'mythroatissore', 'nicetomeetyou', 'noo', 'noproblem',
 'nothankyou', 'nothingelse', 'notrecently', 'notyet', 'now',
 'noworlater', 'ofcourse', 'ok', 'onelikethat', 'please',
 'pleasehelpme', 'pleasesitdown', 'pleasespeakmoreslowly', 'pleasetellme', 'pleasewriteitdown',
 'really', 'righthere', 'rightthere', 'sarah', 'shesanexpert',
 'sorrytobotheryou', 'tellme', 'thanks', 'thanksforeverything', 'thanksforyourhelp',
 'thankyou', 'thankyoumiss', 'thankyousir', 'thankyouverymuch', 'thatsalright',
 'thatsenough', 'thatsfair', 'thatsfine', 'thatsgood', 'thatsgreat',
 'thatsit', 'thatstoobad', 'thatstoolate', 'thatstoomuch', 'thatswrong',
 'thatway', 'thisisverydifficult', 'thisisveryimportant', 'verygoodthanks', 'werelate',
 'whatareyoutwotalkingabout', 'whatdidyouthink', 'whatdoesthismean', 'whatdoesthissay', 'whatdoyouwanttodo',
 'whatisit', 'whatisthat', 'whatsinit', 'whatstheaddress', 'whatsthedate',
 'whatsthis', 'whatsup', 'whatswrong', 'whatsyourname', 'whattimedoesitstart',
 'whattimedoyouthinkyoullarrive', 'whattimeisit', 'whatwouldyouliketoeat', 'whenaretheycoming', 'wherecanifindahospital',
 'wheredoesithurt', 'whereisthebathroom', 'wheresthepharmacy', 'wouldyoulikesomethingtodrink', 'wouldyoulikesomethingtoeat',
 'wouldyoulikesomewater', 'wouldyouliketohavedinnerwithme', 'wouldyoutakeamessageplease', 'yesreally', 'yess',
 'youlookgreat', 'youlooktired', 'yourebeautiful', 'youreright', 'youreverynice',
 'youreverysmart', 'yourewelcome'
]
rb_kudos_boos=[
 'businessisgood', 'certainly', 'cheers', 'excellent',
 'forgetit', 'fuckthat', 'goodafternoon', 'goodeveningsir',
 'goodidea', 'goodluck', 'goodmorning', 'great',
 'happybirthday', 'hesaverygoodstudent', 'hesfasterthanme', 'hesright',
 'hesveryannoying', 'hesveryfamous', 'hesveryhardworking', 'hisroomisverysmall',
 'iagree', 'ibelieveyou', 'idontfeelwell', 'idontlikehim',
 'idontlikeit', 'idontmind', 'idontthinkso', 'idontunderstand',
 'idontwantit', 'idontwantthat', 'idontwanttobotheryou', 'ifeelgood',
 'ilikeher', 'ilikeit', 'ilikeitalianfood', 'iliketowatchtv',
 'illtakeit', 'iloveyou', 'imabeginner', 'imadeamistake',
 'imbored', 'imcold', 'imfull', 'imgood',
 'imgoodandyou', 'imhappy', 'imhot', 'imhungry',
 'imnotafraid', 'imok', 'imsick', 'imsingle',
 'imthirsty', 'imtired', 'imverybusy', 'imworriedtoo',
 'ithinkitsverygood', 'ithinkittastesgood', 'ithinkthoseshoesareverygoodlooking', 'ithinkyouhavetoomanyclothes',
 'ithoughttheclotheswerecheaper', 'ithurtshere', 'itllbecoldthisevening', 'itrainedveryhardtoday',
 'itsdelicious', 'itsfarfromhere', 'itsgoingtobehottoday', 'itsgoingtosnowtoday',
 'itsnotsupposedtoraintoday', 'itsraining', 'itsreallyhot', 'itssupposedtoraintomorrow',
 'itstoolate', 'itsverycoldtoday', 'itsveryimportant', 'itsverywindy',
 'iunderstand', 'iunderstandnow', 'iwanttogiveyouagift', 'iwanttoshowyousomething',
 'noproblem', 'nothankyou', 'ok', 'really',
 'righthere', 'rightthere', 'shesanexpert', 'shesolderthanme',
 'shespretty', 'takeitoutside', 'thanks', 'thanksforeverything',
 'thanksforyourhelp', 'thankyou', 'thankyoumiss', 'thankyousir',
 'thankyouverymuch', 'thatsalright', 'thatsenough', 'thatsfair',
 'thatsfine', 'thatsgood', 'thatsgreat', 'thatsit',
 'thatsmellsbad', 'thatsnotenough', 'thatsnotfair', 'thatsnotright',
 'thatsright', 'thatstoobad', 'thatstooexpensive', 'thatstoolate',
 'thatstoomany', 'thatstoomuch', 'thatswrong', 'thebooksareexpensive',
 'thecarisfixed', 'thisisverydifficult', 'thisisveryimportant', 'thisroomisamess',
 'welikeitverymuch', 'yesreally', 'yess', 'youhaveaverynicecar',
 'youlookgreat', 'youlooklikemysister', 'youlooktired', 'yourchildrenareverywellbehaved',
 'yourebeautiful', 'youreright', 'youresmarterthanhim', 'youreverynice',
 'youreverysmart', 'yourewelcome', 'yourhouseisverynice', 'youspeakenglishverywell'
]
rb_weather=[
 'aboutthreehundredkilometers', 'afew', 'alittle',
 'allday', 'doyouthinkitllraintoday', 'doyouthinkitsgoingtoraintoday',
 'howstheweather', 'idontlikeit', 'imcold',
 'imhot', 'isitcoldoutside', 'isithot',
 'isitraining', 'isitsupposedtoraintomorrow', 'itdependsontheweather',
 'itllbecoldthisevening', 'itrainedveryhardtoday', 'itsgoingtobehottoday',
 'itsnotsupposedtoraintoday', 'itsraining', 'itsreallyhot',
 'itssupposedtoraintomorrow', 'itsverycoldtoday', 'whatwilltheweatherbeliketomorrow'
]
rb_sports = [
'alongtimeago','at7oclockatnight','atwhattime','canibringmyfriend:','cheers',
'chicagoisverydifferentfromboston:','doyouhaveenoughmoney:','doyouhavethenumberforataxi:','doyouknowwhereicangetataxi:','doyouliketowatchtv',
'doyouplayanysports','doyouplaybasketball','doyouthinkitllraintoday:','doyouthinkitsgoingtoraintoday:','doyouthinkitspossible',
'doyouthinkyoullbebackbyeleventhirty:','doyouwantmetocomeandpickyouup:','doyouwanttocomewithme','doyouwanttogowithme','excellent',
'fuckthat:','goodidea:','goodluck:','haveyoubeentoboston','heather',
'hesfasterthanme','hesright:','hesveryannoying','hesveryhardworking','hethinkswedontwanttogo',
'howaboutsaturday','howdoigetthere:','howdoyouknow','howmuchdoesthiscost','howmuchdoioweyou',
'howmuchisit:','howmuchisthat','howmuchisthis','howmuchwillitcost:','howwasthetrip',
'hurry:','iboughtashirtyesterday','icamewithmyfamily:','idliketobuyabottleofwaterplease','idliketogohome:',
'idontcare','idontknow','idontlikehim','idontlikeit:','idontthinkso',
'idontunderstand','idontunderstandwhatyoursaying:','idontwantit:','idontwantthat','idontwanttobotheryou:',
'ifeelgood','iforget','ifyoulikeiticanbuymore','igiveup','ihaveaheadache:',
'ilikeit','ilikeitalianfood','illberightback:','illgiveyouacall','illhavethesamething',
'illpay','illpayfordinner','illpayforthetickets','illtalktoyousoon','imcold',
'imfineandyou','imgoingtogohavedinner','imgoodandyou','imhappy','imhot:',
'imhungry:','imjustkidding','imjustlooking','immarried','imnotafraid:',
'imnotbusy','imnotgoing','imnotreadyyet','imnotsure','imok',
'imready','imsick','imsorry','imthirsty','imtired',
'imworriedtoo','ineedtogotothebathroom','inthirtyminutes','ionlywantasnack','isitclose',
'isithot','isitnearby','isitpossible','isitraining:','isitready',
'isitsupposedtoraintomorrow:','itdependsontheweather','ithinkitsverygood:','ithinkittastesgood','ithinkso:',
'ithurtshere:','itllbecoldthisevening','itrainedveryhardtoday','itsgoingtobehottoday:','itsgoingtosnowtoday',
'itsnotsupposedtoraintoday','itsraining','itsreallyhot','itsverycoldtoday','judy',
'julianne:','noo','noproblem','nothankyou','noworlater',
'ofcourse:','ok:','onelikethat:','ontheleft','ontheright',
'please','sarah:','seeyoulater:','thatsenough:','thatsfair',
'thatsfine','thatsgood','thatsgreat','thatsit','thatsmellsbad',
'thatsnotenough:','thatsnotfair','thatsnotright','thatsright','thatstoobad:',
'thatstooexpensive:','thatstoolate','thatstoomany','thatstoomuch','thatswrong',
'thebigoneorthesmallone','thefoodwasdelicious','therearemanypeoplehere','thewholeday:','theyrewaitingforus',
'whatareyougoingtodotonight:','whatsthis','whatsup','whattimedidyougetup','whattimedidyouwakeup:',
'whattimeisit','whenaretheycoming:','whendidthishappen:','whendidyouarriveinboston','whendowearrive:',
'whendoyougetoffwork','whenwouldyouliketomeet','wherearethetshirts','whyarentyougoing','whyareyoulaughing:',
'whynot','wouldyouaskhimtocomehere','wouldyoulikeaglassofwater','wouldyoulikesomethingtodrink','wouldyoulikesomethingtoeat:','yess'
]
rb_travel=[
 'aboutthreehundredkilometers', 'acrossfromthepostoffice', 'aonewayticket', 'areyouamerican', 'at3oclock',
 'at7oclockatnight', 'atwhattime', 'becarefuldriving', 'doesitoftensnowinthewinterinmassachusetts', 'doyoulikeithere',
 'fuckthat', 'gostraightahead', 'haveagoodtrip', 'haveyouarrived', 'haveyoubeentoboston',
 'hesneverbeentoamerica', 'howdoigetthere', 'howdoigettotheamericanembassy', 'howfarisit', 'howfarisittochicago',
 'howmanymilesisittopennsylvania', 'howmuchisthat', 'howmuchisthis', 'howwasthetrip', 'hurry',
 'idlikeanonsmokingroom', 'idlikeasingleroom', 'idlikethenumberforthehiltonhotelplease', 'idliketocalltheunitedstates', 'idliketomakeareservation',
 'idliketorentacar', 'idliketosendthistoamerica', 'ihavetogotothepostoffice', 'ihopeyouandyourwifehaveanicetrip', 'illberightback',
 'illcallbacklater', 'illcallyouonfriday', 'illcallyouwhenileave', 'imfromamerica', 'istherearestaurantinthehotel',
 'isthereastorenearhere', 'itsnottoofar', 'itsoverthere', 'ittakestwohoursbycar', 'ivealreadyseenit',
 'iveheardtexasisabeautifulplace', 'iveneverdonethat', 'iveseenit', 'judy', 'julianne',
 'maybe', 'mycellphonedoesnthavegoodreception', 'mycellphonedoesntwork', 'myluggageismissing', 'mywatchhasbeenstolen',
 'nobodyisthererightnow', 'noo', 'noproblem', 'nothankyou', 'nothisisthefirsttime',
 'notyet', 'now', 'noworlater', 'ok', 'takemedowntown',
 'takemetothemarriotthotel', 'thanks', 'thanksforeverything', 'thanksforyourhelp', 'thankyou',
 'thankyouverymuch', 'thatstoolate', 'turnaround', 'turnleft', 'turnright',
 'verygoodthanks', 'waiter', 'waitress', 'wecaneatitalianorchinesefood', 'welikeitverymuch',
 'werethereanyproblems', 'whatareyoudoing', 'whereareyou', 'whereareyoufrom', 'whereareyougoing',
 'whereareyougoingtogo', 'wherecanibuytickets', 'wherecanimailthis', 'wherecanirentacar', 'wheredidyougo',
 'wheredoyouwanttogo', 'wheresthepostoffice'
]
rb_help=[
 'amipronouncingitcorrectly', 'areyouok', 'areyouready', 'areyousick', 'areyousure',
 'areyouwaitingforsomeone', 'assoonaspossible', 'atwhattime', 'becarefuldriving', 'callme',
 'callthepolice', 'caniaccesstheinternethere', 'caniborrowsomemoney', 'canibringmyfriend', 'canihaveaglassofwaterplease',
 'canihaveareceiptplease', 'canihavethebillplease', 'canihelpyou', 'canimakeanappointmentfornextwednesday', 'caniseeyourpassportplease',
 'canitakeamessage', 'canitbecheaper', 'canitryiton', 'caniuseyourphone', 'canwehaveamenuplease',
 'canwehavesomemorebreadplease', 'canwesitoverthere', 'canyoucallbacklater', 'canyoucarrythisforme', 'canyoudomeafavor',
 'canyoufixthis', 'canyougivemeanexample', 'canyouhelpme', 'canyouholdthisforme', 'canyoupleasehelpme',
 'canyoupleasesaythatagain', 'canyourecommendagoodrestaurant', 'canyourepeatthatplease', 'canyoushowme', 'canyouspeaklouderplease',
 'canyouthrowthatawayforme', 'canyoutranslatethisforme', 'doyouacceptusdollars', 'doyoubelievethat', 'doyoufeelbetter',
 'doyouhaveanotherone', 'doyouhaveanychildren', 'doyouhaveanycoffee', 'doyouhaveanymoney', 'doyouhaveanythingcheaper',
 'doyouhaveanyvacancies', 'doyouhaveapencil', 'doyouhaveaproblem', 'doyouhaveenoughmoney', 'doyouhavethenumberforataxi',
 'doyouhearthat', 'doyouknowher', 'doyouknowhowmuchitcosts', 'doyouknowhowtocook', 'doyouknowwhatthismeans',
 'doyouknowwhatthissays', 'doyouknowwhereicangetataxi', 'doyouknowwheremyglassesare', 'doyouknowwheresheis', 'doyouneedanything',
 'doyouneedanythingelse', 'doyousellmedicine', 'doyoutakecreditcards', 'doyouunderstand', 'doyouwantmetocomeandpickyouup',
 'doyouwanttocomewithme', 'excuseme', 'excusemewhatdidyousay', 'help', 'howdoigetthere',
 'howdoiusethis', 'howdoyouknow', 'howdoyoupronouncethat', 'howdoyouspellit', 'howfarisit',
 'howisshe', 'howlongareyougoingtostay', 'howlonghaveyoubeenhere', 'howlonghaveyouworkedhere', 'howlongisit',
 'howlongwillittake', 'howmany', 'howmanypeople', 'howmuchalltogether', 'howmuchdoioweyou',
 'howmuchisit', 'howmuchisthat', 'howmuchisthis', 'howmuchwillitcost', 'howmuchwouldyoulike',
 'howoldareyou', 'howstheweather', 'howsworkgoing', 'howwasthetrip', 'idlikearoom',
 'idlikeatablenearthewindow', 'idlikesomewatertooplease', 'idliketobuysomething', 'idliketogoforawalk', 'idliketogohome',
 'idliketogoshopping', 'idliketogotothestore', 'idliketomakeaphonecall', 'idliketomakeareservation', 'idliketousetheinternet',
 'ifyouneedmyhelppleaseletmeknow', 'iknow', 'imgood', 'imhungry', 'imjustlooking',
 'imlost', 'imnotsure', 'imok', 'imready', 'ineedadoctor',
 'ineedanotherkey', 'ineedsometissues', 'ineedthistogettherebytomorrow', 'ineedtochangeclothes', 'ineedtogohome',
 'ineedtogonow', 'ineedtogotobed', 'ineedtogotothebathroom', 'isitclose', 'isitcoldoutside',
 'isitfarfromhere', 'isithot', 'isitnearby', 'isitpossible', 'isitraining',
 'isitready', 'isitsupposedtoraintomorrow', 'isntit', 'isthatenough', 'isthatok',
 'isthebankfar', 'isthereamovietheaternearby', 'iunderstand', 'iveseenit', 'judy',
 'julianne', 'justalittle', 'justamoment', 'maybe', 'mydaughterishere',
 'nonsense', 'noo', 'noproblem', 'nothankyou', 'nothingelse',
 'notrecently', 'notyet', 'now', 'noworlater', 'please',
 'pleasecallme', 'pleasecomein', 'pleasecountthisforme', 'pleasefilloutthisform', 'pleasehelpme',
 'pleasesitdown', 'pleasespeakslower', 'pleasetakemetotheairport', 'pleasetakemetothisaddress', 'pleasetakeoffyourshoes',
 'pleasetellme', 'pleasewaitforme', 'pleasewriteitdown', 'really', 'righthere',
 'rightthere', 'sarah', 'sorryididnthearclearly', 'sorryidonthaveapencil', 'tellhimthatineedtotalktohim',
 'tellme', 'thanks', 'thanksforeverything', 'thanksforyourhelp', 'thankyou',
 'thankyoumiss', 'thankyousir', 'thankyouverymuch', 'thatsalright', 'thatsenough',
 'thatsfair', 'thatsfine', 'thatsgood', 'thatsgreat', 'thatsit',
 'whatareyoudoing', 'whatareyouthinkingabout', 'whatdayaretheycomingover', 'whatdoesthismean', 'whatdoyouthink',
 'whatdoyouwant', 'whatdoyouwanttobuy', 'whatdoyouwanttodo', 'whatshouldiwear', 'whatsinit',
 'whatsize', 'whatsyourfavoritefood', 'whatsyourfavoritemovie', 'whattimearetheyarriving', 'whattimedoesitstart',
 'whattimedoesthemoviestart', 'whattimedoesthestoreopen', 'whatwouldyouliketodrink', 'whatwouldyouliketoeat', 'whenaretheycoming',
 'whenareyoucomingback', 'whenareyougoingtopickupyourfriend', 'whenareyouleaving', 'whenareyoumoving', 'whendidthishappen',
 'whendidyouarriveinboston', 'whendoeshearrive', 'whendoesitarrive', 'whendoesitleave', 'whendoestheplanearrive',
 'whendowearrive', 'whenwouldyouliketomeet', 'whereareyou', 'wherecanifindahospital', 'wherecanimailthis',
 'wherecanirentacar', 'whereishe', 'whereishefrom', 'whereisit', 'whereismyshirt',
 'whereistheairport', 'whereisthebathroom', 'whereisthebusstation', 'whereisthereadoctorwhospeaksenglish', 'whereisthereanatm',
 'wherestheclosestrestaurant', 'wheresthemailbox', 'wheresthenearesthospital', 'wheresthepharmacy', 'wheresthepostoffice',
 'wherewereyou', 'wherewouldyouliketogo', 'wherewouldyouliketomeet', 'whichisbetter', 'whichisthebest',
 'whichone', 'whichonedoyouwant', 'whichoneisbetter', 'whichoneischeaper', 'whichoneisthebest',
 'whichroadshoulditake', 'whyarentyougoing', 'whyareyoulaughing', 'whydidyoudothat', 'whydidyousaythat',
 'whynot', 'willyoucallmeataxiplease', 'willyouhandmeatowelplease', 'willyoupassmethesaltplease', 'willyouputthisinthecarforme',
 'willyouremindme', 'willyoutakemehome', 'wouldyouaskhimtocallmebackplease', 'wouldyouaskhimtocomehere', 'yesreally',
 'yess', 'youreright'
]
conn=PGconn.connect( :hostaddr=>"127.0.0.1", :port=>5432, :dbname=>"talk_dev", :user=>"captdowner", :password=>'sailing')

  rb_frequent.each do |k|
    q="select id from phrases where key='#{k}' order by id";
    res = conn.exec(q);
    res.each do |n|
      q = "INSERT INTO category_phrases(category_id, phrase_id, created_at, updated_at) VALUES(1, #{n['id']}, now(), now());"
      res = conn.exec(q);
    end
  end
