###
# Bengali languages list
###
language:
  ar:    আরবি
  cs:    চেক
  de:    জার্মান
  el:    গ্রিক
  en:    ইংরেজি
  es:    স্প্যানিশ
  fr:    ফরাসি
  hr:    ক্রোয়েশীয়
  hu:    হাঙ্গেরীয়
  it:    ইতালিয়ান
  ja:    জাপানি
  ko:    কোরিয়ান
  lt:    লিথুয়েনীয
  nl:    ওলন্দাজ
  no:    নরওয়েজীয়
  pl:    পোলিশ
  pt:    পর্তুগীজ
  pt-br: ব্রাজিলিয়ান পর্তুগিজ
  ro:    রোমানীয়
  ru:    রাশিয়ান
  sv:    সুয়েডীয়
  th:    থাই
  tr:    তুর্কী
  uk:    ইউক্রেরিয়ান
  vi:    ভিয়েতনামীয়
  zh:    চীনা
