###
# Main menu in Bengali
###
bn:
  visitors:
    index:
      about:        সম্বন্ধে
      are:          হয়? 
      areyou:       আপনি কি ?
      caniyou:      আমি/আপনি কি?
      directions:   পথনির্দেশ
      doyou:        আপনি কি? 
      how:          কেমন?
      i:            আমি 
      oftenused:    প্রায়ই ব্যবহার করা / প্রচলিত
      wherewhen:    কোথায়? কখন?
      welcometo:    স্বাগতম 
