 update phrases set phrase_text='about three hundred kilometers' where id=8830; 
 update phrases set phrase_text='across from the post office' where id=8831;
 update phrases set phrase_text='a few' where id=8832;
 update phrases set phrase_text='a little' where id=8833;
 update phrases set phrase_text='all day' where id=8834;
 update phrases set phrase_text='a long time ago' where id=8835;
 update phrases set phrase_text='Am I pronouncing it correctly?' where id=8836;
 update phrases set phrase_text='Amy is John’s girlfriend' where id=8837;
 update phrases set phrase_text='and you' where id=8838;
 update phrases set phrase_text='Anything else?' where id=8839;
 update phrases set phrase_text='a one way ticket' where id=8840;
 update phrases set phrase_text='Are there any concerts?' where id=8841;
 update phrases set phrase_text='Are they coming this evening?' where id=8842;
 update phrases set phrase_text='Are they the same?' where id=8843;
 update phrases set phrase_text='Are you afraid?' where id=8844;
 update phrases set phrase_text='Are you allergic to anything?' where id=8845;
 update phrases set phrase_text='Are you American?'where id=8846;
 update phrases set phrase_text='Are you busy?' where id=8847;
 update phrases set phrase_text='Are you comfortable?' where id=8848;
 update phrases set phrase_text='Are you coming this evening?' where id=8849;
 update phrases set phrase_text='Are you free tonight?' where id=8850;
 update phrases set phrase_text='Are you going to attend their wedding?' where id=8851;
 update phrases set phrase_text='Are you going to help her?' where id=8852;
 update phrases set phrase_text='Are you going to take a plane?' where id=8853;
 update phrases set phrase_text='Are you here alone?' where id=8854;
 update phrases set phrase_text='Are you hungry?' where id=8855;
 update phrases set phrase_text='Are you married?' where id=8856;
 update phrases set phrase_text='Are you OK?' where id=8857;
 update phrases set phrase_text='Are your children with you?' where id=8858;
 update phrases set phrase_text='Are you ready?' where id=8859;
 update phrases set phrase_text='Are you sick?' where id=8860;
 update phrases set phrase_text='Are you sure?' where id=8861;
 update phrases set phrase_text='Are you waiting for someone?' where id=8862;
 update phrases set phrase_text='Are you working today?' where id=8863;
 update phrases set phrase_text='Are you working tomorrow?' where id=8864;
 update phrases set phrase_text='a round trip ticket' where id=8865;
 update phrases set phrase_text='as soon as possible' where id=8866;
 update phrases set phrase_text='at three oclock' where id=8867;
 update phrases set phrase_text='at three oclock in the afternoon' where id=8868;
 update phrases set phrase_text='at Fifth Street' where id=8869;
 update phrases set phrase_text='at seven oclock at night' where id=8870;
 update phrases set phrase_text='At what time?' where id=8871;
 update phrases set phrase_text='At what time did it happen?' where id=8872;
 update phrases set phrase_text='Be careful' where id=8873;
 update phrases set phrase_text='Be careful driving' where id=8874;
 update phrases set phrase_text='behind the bank' where id=8875;
 update phrases set phrase_text='Be quiet' where id=8876;
 update phrases set phrase_text='Bring me my shirt please' where id=8877;
 update phrases set phrase_text='Business is good' where id=8878;
 update phrases set phrase_text='Call me' where id=8879;
 update phrases set phrase_text='Call the police' where id=8880;
 update phrases set phrase_text='Can I access the internet here?' where id=8881;
 update phrases set phrase_text='Can I borrow some money?' where id=8882;
 update phrases set phrase_text='Can I bring my friend?' where id=8883;
 update phrases set phrase_text='Can I have a glass of water please?' where id=8884;
 update phrases set phrase_text='Can I have a receipt please?' where id=8885;
 update phrases set phrase_text='Can I have the bill please?' where id=8886;
 update phrases set phrase_text='Can I help you?' where id=8887;
 update phrases set phrase_text='Can I make an appointment for next wednesday?' where id=8888;
 update phrases set phrase_text='Can I see your passport please?' where id=8889;
 update phrases set phrase_text='Can I take a message?' where id=8890;
 update phrases set phrase_text='Can it be cheaper?' where id=8891;
 update phrases set phrase_text='Can I try it on?' where id=8892;
 update phrases set phrase_text='Can I use your phone?' where id=8893;
 update phrases set phrase_text='Can we have a menu please?' where id=8894;
 update phrases set phrase_text='Can we have some more bread please?' where id=8895;
 update phrases set phrase_text='Can we sit over there?' where id=8896;
 update phrases set phrase_text='Can you call back later?' where id=8897;
 update phrases set phrase_text='Can you carry this for me?' where id=8898;
 update phrases set phrase_text='Can you do me a favor?' where id=8899;
 update phrases set phrase_text='Can you fix this?'where id=8900;
 update phrases set phrase_text='Can you give me an example?' where id=8901;
 update phrases set phrase_text='Can you help me?' where id=8902;
 update phrases set phrase_text='Can you hold this for me?' where id=8903;
 update phrases set phrase_text='Can you please help me?' where id=8904;
 update phrases set phrase_text='Can you please say that again?' where id=8905;
 update phrases set phrase_text='Can you recommend a good restaurant?' where id=8906;
 update phrases set phrase_text='Can you repeat that please?' where id=8907;
 update phrases set phrase_text='Can you show me?' where id=8908;
 update phrases set phrase_text='Can you speak louder please?' where id=8909;
 update phrases set phrase_text='Can you swim?' where id=8910;
 update phrases set phrase_text='Can you throw that away for me?' where id=8911;
 update phrases set phrase_text='Can you translate this for me?' where id=8912;
 update phrases set phrase_text='Certainly' where id=8913;
 update phrases set phrase_text='Cheers' where id=8914;
 update phrases set phrase_text='Chicago is very different from Boston' where id=8915;
 update phrases set phrase_text='Come here' where id=8916;
 update phrases set phrase_text='Did it snow yesterday?' where id=8917;
 update phrases set phrase_text='Did you come with your family?' where id=8918;
 update phrases set phrase_text='Did you get my email?' where id=8919;
 update phrases set phrase_text='Did your wife like California?' where id=8920;
 update phrases set phrase_text='Did you send me flowers?' where id=8921;
 update phrases set phrase_text='Did you take your medicine?' where id=8922;
 update phrases set phrase_text='Does anyone here speak English?' where id=8923;
 update phrases set phrase_text='Does he like the school?' where id=8924;
 update phrases set phrase_text='Does it often snow in the winter in Massachusetts?' where id=8925;
 update phrases set phrase_text='Does this road go to New York?' where id=8926;
 update phrases set phrase_text='Don’t do that' where id=8927;
 update phrases set phrase_text='Don’t worry' where id=8928;
 update phrases set phrase_text='Do you accept US dollars?' where id=8929;
 update phrases set phrase_text='Do you believe that?' where id=8930;
 update phrases set phrase_text='Do you feel better?' where id=8931;
 update phrases set phrase_text='Do you go to Florida often?' where id=8932;
 update phrases set phrase_text='Do you have a boyfriend?' where id=8933;
 update phrases set phrase_text='Do you have a girlfriend?' where id=8934;
 update phrases set phrase_text='Do you have an appointment?' where id=8935;
 update phrases set phrase_text='Do you have another one?' where id=8936;
 update phrases set phrase_text='Do you have any children?' where id=8937;
 update phrases set phrase_text='Do you have any coffee?' where id=8938;
 update phrases set phrase_text='Do you have any money?' where id=8939;
 update phrases set phrase_text='Do you have anything cheaper?' where id=8940;
 update phrases set phrase_text='Do you have any vacancies?' where id=8941;
 update phrases set phrase_text='Do you have a pencil?' where id=8942;
 update phrases set phrase_text='Do you have a problem?' where id=8943;
 update phrases set phrase_text='Do you have a swimming pool?' where id=8944;
 update phrases set phrase_text='Do you have enough money?' where id=8945;
 update phrases set phrase_text='Do you have the number for a taxi?' where id=8946;
 update phrases set phrase_text='Do you have this in size eleven?' where id=8947;
 update phrases set phrase_text='Do you hear that?'where id=8948;
 update phrases set phrase_text='Do you know her?' where id=8949;
 update phrases set phrase_text='Do you know how much it costs?' where id=8950;
 update phrases set phrase_text='Do you know how to cook?' where id=8951;
 update phrases set phrase_text='Do you know how to get to the Marriott hotel?' where id=8952;
 update phrases set phrase_text='Do you know what this means?' where id=8953;
 update phrases set phrase_text='Do you know what this says?' where id=8954;
 update phrases set phrase_text='Do you know where I can get a taxi?' where id=8955;
 update phrases set phrase_text='Do you know where my glasses are?'where id=8956;
 update phrases set phrase_text='Do you know where she is?' where id=8957;
 update phrases set phrase_text='Do you know where there’s a store that sells towels?' where id=8958;
 update phrases set phrase_text='Do you like it here?' where id=8959;
 update phrases set phrase_text='Do you like the book?' where id=8960;
 update phrases set phrase_text='Do you like to watch TV?' where id=8961;
 update phrases set phrase_text='Do you like your boss?' where id=8962;
 update phrases set phrase_text='Do you like your coworkers?' where id=8963;
 update phrases set phrase_text='Do you need anything?' where id=8964;
 update phrases set phrase_text='Do you need anything else?' where id=8965;
 update phrases set phrase_text='Do you play any sports?' where id=8966;
 update phrases set phrase_text='Do you play basketball?' where id=8967;
 update phrases set phrase_text='Do you sell batteries?' where id=8968;
 update phrases set phrase_text='Do you sell medicine?' where id=8969;
 update phrases set phrase_text='Do you smoke?' where id=8970;
 update phrases set phrase_text='Do you speak English?' where id=8971;
 update phrases set phrase_text='Do you study English?' where id=8972;
 update phrases set phrase_text='Do you take credit cards?' where id=8973;
 update phrases set phrase_text='Do you think it’ll rain today?' where id=8974;
 update phrases set phrase_text='Do you think it’s going to rain today?' where id=8975;
 update phrases set phrase_text='Do you think it’s possible?' where id=8976;
 update phrases set phrase_text='Do you think you’ll be back by eleven thirty?' where id=8977;
 update phrases set phrase_text='Do you understand?' where id=8978;
 update phrases set phrase_text='Do you want me to come and pick you up?' where id=8979;
 update phrases set phrase_text='Do you want to come with me?' where id=8980;
 update phrases set phrase_text='Do you want to go to the movies?' where id=8981;
 update phrases set phrase_text='Do you want to go with me?' where id=8982;
 update phrases set phrase_text='Everyday I get up at six' where id=8983;
 update phrases set phrase_text='Everyone knows it'where id=8984;
 update phrases set phrase_text='Everything is ready' where id=8985;
 update phrases set phrase_text='every week' where id=8986;
 update phrases set phrase_text='excellent' where id=8987;
 update phrases set phrase_text='Excuse me' where id=8988;
 update phrases set phrase_text='Excuse me what did you say' where id=8989;
 update phrases set phrase_text='expiration date' where id=8990;
 update phrases set phrase_text='Fill it up please'where id=8991;
 update phrases set phrase_text='Follow me' where id=8992;
 update phrases set phrase_text='Forget it' where id=8993;
 update phrases set phrase_text='For how many nights?' where id=8994;
 update phrases set phrase_text='from here to there' where id=8995;
 update phrases set phrase_text='from time to time'where id=8996;
 update phrases set phrase_text='Fuck that!' where id=8997;
 update phrases set phrase_text='Give me a call' where id=8998;
 update phrases set phrase_text='Give me the pen' where id=8999;
 update phrases set phrase_text='Good afternoon' where id=9000;
 update phrases set phrase_text='Good evening sir' where id=9001;
 update phrases set phrase_text='Good idea' where id=9002;
 update phrases set phrase_text='Good luck' where id=9003;
 update phrases set phrase_text='Good morning' where id=9004;
 update phrases set phrase_text='Go straight ahead'where id=9005;
 update phrases set phrase_text='Great' where id=9006;
 update phrases set phrase_text='Happy birthday' where id=9007;
 update phrases set phrase_text='Has your brother been to california' where id=9008;
 update phrases set phrase_text='Have a good trip' where id=9009;
 update phrases set phrase_text='Have they met her yet?' where id=9010;
 update phrases set phrase_text='Have you arrived?'where id=9011;
 update phrases set phrase_text='Have you been to Boston?' where id=9012;
 update phrases set phrase_text='Have you been waiting long?' where id=9013;
 update phrases set phrase_text='Have you done this before?' where id=9014;
 update phrases set phrase_text='Have you eaten at that restaurant?' where id=9015;
 update phrases set phrase_text='Have you eaten yet?' where id=9016;
 update phrases set phrase_text='Have you ever had potato soup?' where id=9017;
 update phrases set phrase_text='Have you finished studying?' where id=9018;
 update phrases set phrase_text='Have you seen this movie?' where id=9019;
 update phrases set phrase_text='He always does that for me' where id=9020;
 update phrases set phrase_text='Heather' where id=9021;
 update phrases set phrase_text='He broke the window' where id=9022;
 update phrases set phrase_text='He doesn’t look like a nurse' where id=9023;
 update phrases set phrase_text='He has a nice car'where id=9024;
 update phrases set phrase_text='He likes it very much' where id=9025;
 update phrases set phrase_text='He likes juice but he doesn’t like milk' where id=9026;
 update phrases set phrase_text='He’ll be back in twenty minutes' where id=9027;
 update phrases set phrase_text='Hello' where id=9028;
 update phrases set phrase_text='Help' where id=9029;
 update phrases set phrase_text='He needs some new clothes' where id=9030;
 update phrases set phrase_text='He never gives me anything' where id=9031;
 update phrases set phrase_text='Here it is' where id=9032;
 update phrases set phrase_text='Here’s my number' where id=9033;
 update phrases set phrase_text='Here’s your order'where id=9034;
 update phrases set phrase_text='Here’s your salad'where id=9035;
 update phrases set phrase_text='Here you are' where id=9036;
 update phrases set phrase_text='He said this is a nice place' where id=9037;
 update phrases set phrase_text='He said you like to watch movies' where id=9038;
 update phrases set phrase_text='He’s an American' where id=9039;
 update phrases set phrase_text='He’s an engineer' where id=9040;
 update phrases set phrase_text='He’s a very good student' where id=9041;
 update phrases set phrase_text='He’s coming soon' where id=9042;
 update phrases set phrase_text='He’s faster than me' where id=9043;
 update phrases set phrase_text='He’s in the kitchen' where id=9044;
 update phrases set phrase_text='He’s never been to America' where id=9045;
 update phrases set phrase_text='He’s not in right now' where id=9046;
 update phrases set phrase_text='He’s right' where id=9047;
 update phrases set phrase_text='He studies at Boston University' where id=9048;
 update phrases set phrase_text='He’s very annoying' where id=9049;
 update phrases set phrase_text='He’s very famous' where id=9050;
 update phrases set phrase_text='He’s very hard working' where id=9051;
 update phrases set phrase_text='He thinks we don’t want to go' where id=9052;
 update phrases set phrase_text='He works at a computer company in New York' where id=9053;
 update phrases set phrase_text='Hi, is Mrs. Smith there please' where id=9054;
 update phrases set phrase_text='His family is coming tomorrow' where id=9055;
 update phrases set phrase_text='His room is very small' where id=9056;
 update phrases set phrase_text='his son' where id=9057;
 update phrases set phrase_text='How about Saturday?' where id=9058;
 update phrases set phrase_text='How are you?' where id=9059;
 update phrases set phrase_text='How are you paying?' where id=9060;
 update phrases set phrase_text='How are your parents?' where id=9061;
 update phrases set phrase_text='How does it taste?' where id=9062;
 update phrases set phrase_text='How do I get there?' where id=9063;
 update phrases set phrase_text='How do I get to Daniel Street?' where id=9064;
 update phrases set phrase_text='How do I get to the American embassy?' where id=9065;
 update phrases set phrase_text='How do I use this?' where id=9066;
 update phrases set phrase_text='How do you know?' where id=9067;
 update phrases set phrase_text='How do you pronounce that?' where id=9068;
 update phrases set phrase_text='How do you say it in English?' where id=9069;
 update phrases set phrase_text='How do you spell it?' where id=9070;
 update phrases set phrase_text='How do you spell the word Seattle?' where id=9071;
 update phrases set phrase_text='How far is it?' where id=9072;
 update phrases set phrase_text='How far is it to Chicago?' where id=9073;
 update phrases set phrase_text='How is she?' where id=9074;
 update phrases set phrase_text='How long are you going to stay?' where id=9075;
 update phrases set phrase_text='How long are you going to stay in California?' where id=9076;
 update phrases set phrase_text='How long does it take by car?' where id=9077;
 update phrases set phrase_text='How long does it take to get to Georgia?' where id=9078;
 update phrases set phrase_text='How long have you been here?' where id=9079;
 update phrases set phrase_text='How long have you worked here?' where id=9080;
 update phrases set phrase_text='How long is it?' where id=9081;
 update phrases set phrase_text='How long is the flight?' where id=9082;
 update phrases set phrase_text='How long will it take?' where id=9083;
 update phrases set phrase_text='How long will you be staying?' where id=9084;
 update phrases set phrase_text='How many?' where id=9085;
 update phrases set phrase_text='How many children do you have?' where id=9086;
 update phrases set phrase_text='How many hours a week do you work?' where id=9087;
 update phrases set phrase_text='How many languages do you speak?' where id=9088;
 update phrases set phrase_text='How many miles is it to Pennsylvania?' where id=9089;
 update phrases set phrase_text='How many people?' where id=9090;
 update phrases set phrase_text='How many people are there in New York?' where id=9091;
 update phrases set phrase_text='How many people do you have in your family?' where id=9092;
 update phrases set phrase_text='How much all together?' where id=9093;
 update phrases set phrase_text='How much are these earrings?' where id=9094;
 update phrases set phrase_text='How much does it cost per day?' where id=9095;
 update phrases set phrase_text='How much does this cost?' where id=9096;
 update phrases set phrase_text='How much do I owe you?' where id=9097;
 update phrases set phrase_text='How much is it?' where id=9098;
 update phrases set phrase_text='How much is it to go to Miami?' where id=9099;
 update phrases set phrase_text='How much is that?'where id=9100;
 update phrases set phrase_text='How much is this?'where id=9101;
 update phrases set phrase_text='How much money do you have?' where id=9102;
 update phrases set phrase_text='How much money do you make?' where id=9103;
 update phrases set phrase_text='How much will it cost?' where id=9104;
 update phrases set phrase_text='How much would you like?' where id=9105;
 update phrases set phrase_text='How old are you?' where id=9106;
 update phrases set phrase_text='How’s business?' where id=9107;
 update phrases set phrase_text='How’s the weather?' where id=9108;
 update phrases set phrase_text='How’s work going?'where id=9109;
 update phrases set phrase_text='How tall are you?'where id=9110;
 update phrases set phrase_text='How was the movie?' where id=9111;
 update phrases set phrase_text='How was the trip?'where id=9112;
 update phrases set phrase_text='Hurry' where id=9113;
 update phrases set phrase_text='I agree' where id=9114;
 update phrases set phrase_text='I ate already' where id=9115;
 update phrases set phrase_text='I believe you' where id=9116;
 update phrases set phrase_text='I bought a shirt yesterday' where id=9117;
 update phrases set phrase_text='I came with my family' where id=9118;
 update phrases set phrase_text='I can swim' where id=9119;
 update phrases set phrase_text='I can’t hear you' where id=9120;
 update phrases set phrase_text='I can’t hear you clearly' where id=9121;
 update phrases set phrase_text='I’d like a map of the city' where id=9122;
 update phrases set phrase_text='I’d like a non smoking room' where id=9123;
 update phrases set phrase_text='I’d like a room' where id=9124;
 update phrases set phrase_text='I’d like a room with two beds please' where id=9125;
 update phrases set phrase_text='I’d like a single room' where id=9126;
 update phrases set phrase_text='I’d like a table near the window' where id=9127;
 update phrases set phrase_text='I’d like some water too please' where id=9128;
 update phrases set phrase_text='I’d like the number for the Hilton hotel please' where id=9129;
 update phrases set phrase_text='I’d like to buy a bottle of water please' where id=9130;
 update phrases set phrase_text='I’d like to buy a phone card please' where id=9131;
 update phrases set phrase_text='I’d like to buy something' where id=9132;
 update phrases set phrase_text='I’d like to call the United States' where id=9133;
 update phrases set phrase_text='I’d like to eat at Fifth Street restaurant' where id=9134;
 update phrases set phrase_text='I’d like to exchange this for dollars' where id=9135;
 update phrases set phrase_text='I’d like to go for a walk' where id=9136;
 update phrases set phrase_text='I’d like to go home' where id=9137;
 update phrases set phrase_text='I’d like to go shopping' where id=9138;
 update phrases set phrase_text='I’d like to go to the store' where id=9139;
 update phrases set phrase_text='I’d like to make a phone call' where id=9140;
 update phrases set phrase_text='I’d like to make a reservation' where id=9141;
 update phrases set phrase_text='I’d like to rent a car' where id=9142;
 update phrases set phrase_text='I’d like to send a fax' where id=9143;
 update phrases set phrase_text='I’d like to send this to America' where id=9144;
 update phrases set phrase_text='I’d like to speak to mr smith please' where id=9145;
 update phrases set phrase_text='I’d like to use the internet' where id=9146;
 update phrases set phrase_text='I don’t care' where id=9147;
 update phrases set phrase_text='I don’t feel well'where id=9148;
 update phrases set phrase_text='I don’t have a girlfriend' where id=9149;
 update phrases set phrase_text='I don’t have any money' where id=9150;
 update phrases set phrase_text='I don’t have time right now' where id=9151;
 update phrases set phrase_text='I don’t know' where id=9152;
 update phrases set phrase_text='I don’t know how to use it' where id=9153;
 update phrases set phrase_text='I don’t like him' where id=9154;
 update phrases set phrase_text='I don’t like it' where id=9155;
 update phrases set phrase_text='I don’t mind' where id=9156;
 update phrases set phrase_text='I don’t speak English very well' where id=9157;
 update phrases set phrase_text='I don’t speak very well' where id=9158;
 update phrases set phrase_text='I don’t think so' where id=9159;
 update phrases set phrase_text='I don’t understand' where id=9160;
 update phrases set phrase_text='I don’t understand what your saying' where id=9161;
 update phrases set phrase_text='I don’t want it' where id=9162;
 update phrases set phrase_text='I don’t want that'where id=9163;
 update phrases set phrase_text='I don’t want to bother you' where id=9164;
 update phrases set phrase_text='I feel good' where id=9165;
 update phrases set phrase_text='I forget' where id=9166;
 update phrases set phrase_text='if you like it I can buy more' where id=9167;
 update phrases set phrase_text='if you need my help please let me know' where id=9168;
 update phrases set phrase_text='I get off work at six' where id=9169;
 update phrases set phrase_text='I give up' where id=9170;
 update phrases set phrase_text='I got in an accident' where id=9171;
 update phrases set phrase_text='I have a cold' where id=9172;
 update phrases set phrase_text='I have a headache'where id=9173;
 update phrases set phrase_text='I have a lot of things to do' where id=9174;
 update phrases set phrase_text='I have a question I want to ask you' where id=9175;
 update phrases set phrase_text='I have a reservation' where id=9176;
 update phrases set phrase_text='I have money' where id=9177;
 update phrases set phrase_text='I haven’t been there' where id=9178;
 update phrases set phrase_text='I haven’t finished eating' where id=9179;
 update phrases set phrase_text='I haven’t had lunch yet' where id=9180;
 update phrases set phrase_text='I have one in my car' where id=9181;
 update phrases set phrase_text='I have pain in my arm' where id=9182;
 update phrases set phrase_text='I have three children two girls and one boy' where id=9183;
 update phrases set phrase_text='I have to go to the post office' where id=9184;
 update phrases set phrase_text='I have to wash my clothes' where id=9185;
 update phrases set phrase_text='I have two sisters' where id=9186;
 update phrases set phrase_text='I hope you and your wife have a nice trip' where id=9187;
 update phrases set phrase_text='I know' where id=9188;
 update phrases set phrase_text='I like her' where id=9189;
 update phrases set phrase_text='I like it' where id=9190;
 update phrases set phrase_text='I like Italian food' where id=9191;
 update phrases set phrase_text='I like to watch TV' where id=9192;
 update phrases set phrase_text='I live in california' where id=9193;
 update phrases set phrase_text='I’ll be right back' where id=9194;
 update phrases set phrase_text='I’ll call back later' where id=9195;
 update phrases set phrase_text='I’ll call you on Friday' where id=9196;
 update phrases set phrase_text='I’ll call you when I leave' where id=9197;
 update phrases set phrase_text='I’ll come back later' where id=9198;
 update phrases set phrase_text='I’ll give you a call' where id=9199;
 update phrases set phrase_text='I’ll have a cup of tea please' where id=9200;
 update phrases set phrase_text='I’ll have a glass of water please'where id=9201;
 update phrases set phrase_text='I’ll have the same thing' where id=9202;
 update phrases set phrase_text='I’ll pay' where id=9203;
 update phrases set phrase_text='I’ll pay for dinner' where id=9204;
 update phrases set phrase_text='I’ll pay for the tickets' where id=9205;
 update phrases set phrase_text='I’ll take it' where id=9206;
 update phrases set phrase_text='I’ll take that one also' where id=9207;
 update phrases set phrase_text='I’ll take you to the bus stop' where id=9208;
 update phrases set phrase_text='I’ll talk to you soon' where id=9209;
 update phrases set phrase_text='I’ll teach you' where id=9210;
 update phrases set phrase_text='I’ll tell him you called' where id=9211;
 update phrases set phrase_text='I lost my watch' where id=9212;
 update phrases set phrase_text='I love you' where id=9213;
 update phrases set phrase_text='I’m a beginner' where id=9214;
 update phrases set phrase_text='I made a mistake' where id=9215;
 update phrases set phrase_text='I made this cake' where id=9216;
 update phrases set phrase_text='I’m allergic to seafood' where id=9217;
 update phrases set phrase_text='I’m American' where id=9218;
 update phrases set phrase_text='I’m an American' where id=9219;
 update phrases set phrase_text='I’m a size eight' where id=9220;
 update phrases set phrase_text='I’m a teacher' where id=9221;
 update phrases set phrase_text='I’m bored' where id=9222;
 update phrases set phrase_text='I’m cleaning my room' where id=9223;
 update phrases set phrase_text='I’m cold' where id=9224;
 update phrases set phrase_text='I’m coming right now' where id=9225;
 update phrases set phrase_text='I’m coming to pick you up' where id=9226;
 update phrases set phrase_text='I’m fine and you' where id=9227;
 update phrases set phrase_text='I’m from America' where id=9228;
 update phrases set phrase_text='I’m full' where id=9229;
 update phrases set phrase_text='I’m getting ready to go out' where id=9230;
 update phrases set phrase_text='I’m going home in four days' where id=9231;
 update phrases set phrase_text='I’m going to America next year' where id=9232;
 update phrases set phrase_text='I’m going to bed' where id=9233;
 update phrases set phrase_text='I’m going to go have dinner' where id=9234;
 update phrases set phrase_text='I’m going to leave' where id=9235;
 update phrases set phrase_text='I’m good' where id=9236;
 update phrases set phrase_text='I’m good and you' where id=9237;
 update phrases set phrase_text='I’m happy' where id=9238;
 update phrases set phrase_text='I’m here on business' where id=9239;
 update phrases set phrase_text='I’m hot' where id=9240;
 update phrases set phrase_text='I’m hungry' where id=9241;
 update phrases set phrase_text='I’m just kidding' where id=9242;
 update phrases set phrase_text='I’m just looking' where id=9243;
 update phrases set phrase_text='I’m leaving tomorrow' where id=9244;
 update phrases set phrase_text='I’m looking for the post office' where id=9245;
 update phrases set phrase_text='I’m lost' where id=9246;
 update phrases set phrase_text='I’m married' where id=9247;
 update phrases set phrase_text='I’m not afraid' where id=9248;
 update phrases set phrase_text='I’m not American' where id=9249;
 update phrases set phrase_text='I’m not busy' where id=9250;
 update phrases set phrase_text='I’m not going' where id=9251;
 update phrases set phrase_text='I’m not married' where id=9252;
 update phrases set phrase_text='I’m not ready yet'where id=9253;
 update phrases set phrase_text='I’m not sure' where id=9254;
 update phrases set phrase_text='I’m OK' where id=9255;
 update phrases set phrase_text='I’m on hold' where id=9256;
 update phrases set phrase_text='I’m ready' where id=9257;
 update phrases set phrase_text='I’m self employed'where id=9258;
 update phrases set phrase_text='I’m sick' where id=9259;
 update phrases set phrase_text='I’m single' where id=9260;
 update phrases set phrase_text='I’m six foot two' where id=9261;
 update phrases set phrase_text='I’m sorry' where id=9262;
 update phrases set phrase_text='I’m sorry we’re sold out' where id=9263;
 update phrases set phrase_text='I’m thirsty' where id=9264;
 update phrases set phrase_text='I’m thirty two' where id=9265;
 update phrases set phrase_text='I’m tired' where id=9266;
 update phrases set phrase_text='I’m twenty six years old' where id=9267;
 update phrases set phrase_text='I’m very busy' where id=9268;
 update phrases set phrase_text='I’m very busy I don’t have time now' where id=9269;
 update phrases set phrase_text='I’m very well thank you' where id=9270;
 update phrases set phrase_text='I’m waiting for you' where id=9271;
 update phrases set phrase_text='I’m worried too' where id=9272;
 update phrases set phrase_text='I need a doctor' where id=9273;
 update phrases set phrase_text='I need another key' where id=9274;
 update phrases set phrase_text='I need some tissues' where id=9275;
 update phrases set phrase_text='I need this to get there by tomorrow' where id=9276;
 update phrases set phrase_text='I need to change clothes' where id=9277;
 update phrases set phrase_text='I need to go home'where id=9278;
 update phrases set phrase_text='I need to go now' where id=9279;
 update phrases set phrase_text='I need to go to bed' where id=9280;
 update phrases set phrase_text='I need to go to the bathroom' where id=9281;
 update phrases set phrase_text='I need to practice my English' where id=9282;
 update phrases set phrase_text='in thirty minutes'where id=9283;
 update phrases set phrase_text='I only have five dollars' where id=9284;
 update phrases set phrase_text='I only want a snack' where id=9285;
 update phrases set phrase_text='I remember' where id=9286;
 update phrases set phrase_text='Is anyone else coming?' where id=9287;
 update phrases set phrase_text='Is everything OK?'where id=9288;
 update phrases set phrase_text='Is it close?' where id=9289;
 update phrases set phrase_text='Is it cold outside?' where id=9290;
 update phrases set phrase_text='Is it far from here?' where id=9291;
 update phrases set phrase_text='Is it hot?' where id=9292;
 update phrases set phrase_text='Is it nearby?' where id=9293;
 update phrases set phrase_text='Is it possible?' where id=9294;
 update phrases set phrase_text='Is it raining?' where id=9295;
 update phrases set phrase_text='Is it ready?' where id=9296;
 update phrases set phrase_text='Is it supposed to rain tomorrow?' where id=9297;
 update phrases set phrase_text='Is John here?' where id=9298;
 update phrases set phrase_text='Is John there please?' where id=9299;
 update phrases set phrase_text='Is Mr. Smith an American?' where id=9300;
 update phrases set phrase_text='Isn’t it?' where id=9301;
 update phrases set phrase_text='I speak a little English' where id=9302;
 update phrases set phrase_text='I speak two languages' where id=9303;
 update phrases set phrase_text='Is that enough?' where id=9304;
 update phrases set phrase_text='Is that OK?' where id=9305;
 update phrases set phrase_text='Is the bank far?' where id=9306;
 update phrases set phrase_text='Is there air conditioning in the room?' where id=9307;
 update phrases set phrase_text='Is there a movie theater nearby?' where id=9308;
 update phrases set phrase_text='Is there an English speaking guide?' where id=9309;
 update phrases set phrase_text='Is there a night club in town?' where id=9310;
 update phrases set phrase_text='Is there any mail for me?' where id=9311;
 update phrases set phrase_text='Is there anything cheaper?' where id=9312;
 update phrases set phrase_text='Is there a restaurant in the hotel?' where id=9313;
 update phrases set phrase_text='Is there a store near here?' where id=9314;
 update phrases set phrase_text='Is this a safe area?' where id=9315;
 update phrases set phrase_text='Is this Mr. Smith?' where id=9316;
 update phrases set phrase_text='Is this pen yours?' where id=9317;
 update phrases set phrase_text='Is this the bus to NY?' where id=9318;
 update phrases set phrase_text='Is this your book?' where id=9319;
 update phrases set phrase_text='I still have a lot of things to buy' where id=9320;
 update phrases set phrase_text='I still have a lot of work to do' where id=9321;
 update phrases set phrase_text='I still haven’t decided' where id=9322;
 update phrases set phrase_text='I still have to brush my teeth and take a shower' where id=9323;
 update phrases set phrase_text='Is your father home?' where id=9324;
 update phrases set phrase_text='Is your house like this one?' where id=9325;
 update phrases set phrase_text='Is your husband also from Boston?'where id=9326;
 update phrases set phrase_text='Is your son here?'where id=9327;
 update phrases set phrase_text='It costs twenty dollars per hour' where id=9328;
 update phrases set phrase_text='It depends on the weather' where id=9329;
 update phrases set phrase_text='I think I need to see a doctor' where id=9330;
 update phrases set phrase_text='I think its very good' where id=9331;
 update phrases set phrase_text='I think it tastes good' where id=9332;
 update phrases set phrase_text='I think so' where id=9333;
 update phrases set phrase_text='I think those shoes are very good looking' where id=9334;
 update phrases set phrase_text='I think you have too many clothes'where id=9335;
 update phrases set phrase_text='I thought he said something else' where id=9336;
 update phrases set phrase_text='I thought the clothes were cheaper' where id=9337;
 update phrases set phrase_text='It hurts here' where id=9338;
 update phrases set phrase_text='It’ll be cold this evening' where id=9339;
 update phrases set phrase_text='It rained very hard today' where id=9340;
 update phrases set phrase_text='I trust you' where id=9341;
 update phrases set phrase_text='It’s August twenty fifth' where id=9342;
 update phrases set phrase_text='It’s delicious' where id=9343;
 update phrases set phrase_text='It’s eight forty-five' where id=9344;
 update phrases set phrase_text='It’s eleven thirty' where id=9345;
 update phrases set phrase_text='It’s far from here' where id=9346;
 update phrases set phrase_text='It’s going to be hot today' where id=9347;
 update phrases set phrase_text='It’s going to snow today' where id=9348;
 update phrases set phrase_text='It’s half past eleven' where id=9349;
 update phrases set phrase_text='It’s here' where id=9350;
 update phrases set phrase_text='It’s less than five dollars' where id=9351;
 update phrases set phrase_text='It’s longer than two miles' where id=9352;
 update phrases set phrase_text='It’s mine' where id=9353;
 update phrases set phrase_text='It’s more than five dollars' where id=9354;
 update phrases set phrase_text='It’s near the supermarket' where id=9355;
 update phrases set phrase_text='It’s north of here' where id=9356;
 update phrases set phrase_text='It’s not supposed to rain today' where id=9357;
 update phrases set phrase_text='It’s not too far' where id=9358;
 update phrases set phrase_text='It’s not very expensive' where id=9359;
 update phrases set phrase_text='It’s OK' where id=9360;
 update phrases set phrase_text='It’s on Seventh Street' where id=9361;
 update phrases set phrase_text='It’s over there' where id=9362;
 update phrases set phrase_text='It’s quarter past nine' where id=9363;
 update phrases set phrase_text='It’s quarter to seven' where id=9364;
 update phrases set phrase_text='It’s raining' where id=9365;
 update phrases set phrase_text='It’s really hot' where id=9366;
 update phrases set phrase_text='It’s seventeen dollars' where id=9367;
 update phrases set phrase_text='It’s shorter than three miles' where id=9368;
 update phrases set phrase_text='It’s six' where id=9369;
 update phrases set phrase_text='It’s supposed to rain tomorrow' where id=9370;
 update phrases set phrase_text='It’s there' where id=9371;
 update phrases set phrase_text='It’s too late' where id=9372;
 update phrases set phrase_text='It’s very cold today' where id=9373;
 update phrases set phrase_text='It’s very important' where id=9374;
 update phrases set phrase_text='It’s very windy' where id=9375;
 update phrases set phrase_text='It takes two hours by car' where id=9376;
 update phrases set phrase_text='It will arrive shortly' where id=9377;
 update phrases set phrase_text='I understand' where id=9378;
 update phrases set phrase_text='I understand now' where id=9379;
 update phrases set phrase_text='I usually drink coffee at breakfast' where id=9380;
 update phrases set phrase_text='I’ve already seen it' where id=9381;
 update phrases set phrase_text='I’ve been here for two days' where id=9382;
 update phrases set phrase_text='I’ve been there' where id=9383;
 update phrases set phrase_text='I’ve heard Texas is a beautiful place' where id=9384;
 update phrases set phrase_text='I’ve never done that' where id=9385;
 update phrases set phrase_text='I’ve never seen that before' where id=9386;
 update phrases set phrase_text='I’ve seen it' where id=9387;
 update phrases set phrase_text='I’ve worked there for five years' where id=9388;
 update phrases set phrase_text='I want to buy something' where id=9389;
 update phrases set phrase_text='I want to contact our embassy' where id=9390;
 update phrases set phrase_text='I want to give you a gift' where id=9391;
 update phrases set phrase_text='I want to send this package to the United States' where id=9392;
 update phrases set phrase_text='I want to show you something' where id=9393;
 update phrases set phrase_text='I was about to leave the restaurant when my friends arrived' where id=9394;
 update phrases set phrase_text='I was going to the library' where id=9395;
 update phrases set phrase_text='I was in the library' where id=9396;
 update phrases set phrase_text='I went to the supermarket and then to the computer store' where id=9397;
 update phrases set phrase_text='I wish I had one' where id=9398;
 update phrases set phrase_text='John is going on vacation tomorrow' where id=9399;
 update phrases set phrase_text='Judy' where id=9400;
 update phrases set phrase_text='Julianne' where id=9401;
 update phrases set phrase_text='June third' where id=9402;
 update phrases set phrase_text='Just a little' where id=9403;
 update phrases set phrase_text='Just a moment' where id=9404;
 update phrases set phrase_text='Let me check' where id=9405;
 update phrases set phrase_text='Let me think about it' where id=9406;
 update phrases set phrase_text='Let’s eat' where id=9407;
 update phrases set phrase_text='Let’s go' where id=9408;
 update phrases set phrase_text='Let’s go have a look' where id=9409;
 update phrases set phrase_text='Let’s meet in front of the hotel' where id=9410;
 update phrases set phrase_text='Let’s practice English' where id=9411;
 update phrases set phrase_text='Let’s share' where id=9412;
 update phrases set phrase_text='Male or female' where id=9413;
 update phrases set phrase_text='Maybe' where id=9414;
 update phrases set phrase_text='May I speak to Mrs. Smith please' where id=9415;
 update phrases set phrase_text='More than that' where id=9416;
 update phrases set phrase_text='More than two hundred miles' where id=9417;
 update phrases set phrase_text='My birthday is August twentyth' where id=9418;
 update phrases set phrase_text='My car isn’t working' where id=9419;
 update phrases set phrase_text='My car was hit by another car' where id=9420;
 update phrases set phrase_text='My cell phone doesn’t have good reception' where id=9421;
 update phrases set phrase_text='My cell phone doesn’t work' where id=9422;
 update phrases set phrase_text='My daughter is here' where id=9423;
 update phrases set phrase_text='My father has been there' where id=9424;
 update phrases set phrase_text='My father is a lawyer' where id=9425;
 update phrases set phrase_text='My friend is American' where id=9426;
 update phrases set phrase_text='My grandmother passed away last year' where id=9427;
 update phrases set phrase_text='My house is close to the bank' where id=9428;
 update phrases set phrase_text='My luggage is missing' where id=9429;
 update phrases set phrase_text='My name is john smith' where id=9430;
 update phrases set phrase_text='My son' where id=9431;
 update phrases set phrase_text='My son studies computers' where id=9432;
 update phrases set phrase_text='My stomach hurts' where id=9433;
 update phrases set phrase_text='My throat is sore'where id=9434;
 update phrases set phrase_text='My watch has been stolen' where id=9435;
 update phrases set phrase_text='near the bank' where id=9436;
 update phrases set phrase_text='Nevermind' where id=9437;
 update phrases set phrase_text='Next time' where id=9438;
 update phrases set phrase_text='Nice to meet you' where id=9439;
 update phrases set phrase_text='No, I’m American' where id=9440;
 update phrases set phrase_text='No, this is the first time' where id=9441;
 update phrases set phrase_text='Nobody is helping us' where id=9442;
 update phrases set phrase_text='Nobody is there right now' where id=9443;
 update phrases set phrase_text='Nonsense' where id=9444;
 update phrases set phrase_text='No' where id=9445;
 update phrases set phrase_text='No problem' where id=9446;
 update phrases set phrase_text='No thank you' where id=9447;
 update phrases set phrase_text='Nothing else' where id=9448;
 update phrases set phrase_text='Not recently' where id=9449;
 update phrases set phrase_text='Not yet' where id=9450;
 update phrases set phrase_text='Now' where id=9451;
 update phrases set phrase_text='Now or later' where id=9452;
 update phrases set phrase_text='October twenty second' where id=9453;
 update phrases set phrase_text='Of course' where id=9454;
 update phrases set phrase_text='OK' where id=9455;
 update phrases set phrase_text='One like that' where id=9456;
 update phrases set phrase_text='One ticket to New York please' where id=9457;
 update phrases set phrase_text='One way or round trip?' where id=9458;
 update phrases set phrase_text='on the left' where id=9459;
 update phrases set phrase_text='on the right' where id=9460;
 update phrases set phrase_text='on the second floor' where id=9461;
 update phrases set phrase_text='Open the door' where id=9462;
 update phrases set phrase_text='Open the window' where id=9463;
 update phrases set phrase_text='Our children are in America' where id=9464;
 update phrases set phrase_text='outside the hotel'where id=9465;
 update phrases set phrase_text='over here' where id=9466;
 update phrases set phrase_text='over there' where id=9467;
 update phrases set phrase_text='Pickup your clothes' where id=9468;
 update phrases set phrase_text='Please' where id=9469;
 update phrases set phrase_text='Please call me' where id=9470;
 update phrases set phrase_text='Please come in' where id=9471;
 update phrases set phrase_text='Please count this for me' where id=9472;
 update phrases set phrase_text='Please fill out this form' where id=9473;
 update phrases set phrase_text='Please help me?' where id=9474;
 update phrases set phrase_text='Please sit down' where id=9475;
 update phrases set phrase_text='Please speak English' where id=9476;
 update phrases set phrase_text='Please speak more slowly' where id=9477;
 update phrases set phrase_text='Please speak slower' where id=9478;
 update phrases set phrase_text='Please take me to the airport' where id=9479;
 update phrases set phrase_text='Please take me to this address' where id=9480;
 update phrases set phrase_text='Please take off your shoes' where id=9481;
 update phrases set phrase_text='Please tell her John called' where id=9482;
 update phrases set phrase_text='Please tell me' where id=9483;
 update phrases set phrase_text='Please wait for me' where id=9484;
 update phrases set phrase_text='Please write it down' where id=9485;
 update phrases set phrase_text='Really' where id=9486;
 update phrases set phrase_text='Right here' where id=9487;
 update phrases set phrase_text='Right there' where id=9488;
 update phrases set phrase_text='Sarah' where id=9489;
 update phrases set phrase_text='See you later' where id=9490;
 update phrases set phrase_text='See you tomorrow' where id=9491;
 update phrases set phrase_text='See you tonight' where id=9492;
 update phrases set phrase_text='She’s an expert' where id=9493;
 update phrases set phrase_text='She’s going with me tomorrow' where id=9494;
 update phrases set phrase_text='She’s older than me' where id=9495;
 update phrases set phrase_text='She’s pretty' where id=9496;
 update phrases set phrase_text='She wants to know when your coming' where id=9497;
 update phrases set phrase_text='Should I wait' where id=9498;
 update phrases set phrase_text='Some books' where id=9499;
 update phrases set phrase_text='Someone does that for me' where id=9500;
 update phrases set phrase_text='Someone is coming'where id=9501;
 update phrases set phrase_text='Sometimes I go to sleep at eleven sometimes at eleven thirty' where id=9502;
 update phrases set phrase_text='Sorry, I didnt hear clearly' where id=9503;
 update phrases set phrase_text='Sorry, I don’t have a pencil' where id=9504;
 update phrases set phrase_text='Sorry, I think I have the wrong number' where id=9505;
 update phrases set phrase_text='Sorry, to bother you' where id=9506;
 update phrases set phrase_text='Sorry, we don’t accept credit cards' where id=9507;
 update phrases set phrase_text='Sorry, we don’t have any' where id=9508;
 update phrases set phrase_text='Sorry, we don’t have any vacancies' where id=9509;
 update phrases set phrase_text='Sorry, we only accept cash' where id=9510;
 update phrases set phrase_text='Start the car' where id=9511;
 update phrases set phrase_text='Stop' where id=9512;
 update phrases set phrase_text='Take a chance' where id=9513;
 update phrases set phrase_text='Take it outside' where id=9514;
 update phrases set phrase_text='Take me downtown' where id=9515;
 update phrases set phrase_text='Take me to the Marriott hotel' where id=9516;
 update phrases set phrase_text='Take this medicine' where id=9517;
 update phrases set phrase_text='Tell him that I need to talk to him' where id=9518;
 update phrases set phrase_text='Tell me' where id=9519;
 update phrases set phrase_text='Thanks' where id=9520;
 update phrases set phrase_text='Thanks for everything' where id=9521;
 update phrases set phrase_text='Thanks for your help' where id=9522;
 update phrases set phrase_text='Thank you' where id=9523;
 update phrases set phrase_text='Thank you miss' where id=9524;
 update phrases set phrase_text='Thank you sir' where id=9525;
 update phrases set phrase_text='Thank you very much' where id=9526;
 update phrases set phrase_text='That car is similar to my car' where id=9527;
 update phrases set phrase_text='That car over there is mine' where id=9528;
 update phrases set phrase_text='That looks great' where id=9529;
 update phrases set phrase_text='That looks old' where id=9530;
 update phrases set phrase_text='That means friend'where id=9531;
 update phrases set phrase_text='That restaurant is not expensive' where id=9532;
 update phrases set phrase_text='That’s a good school' where id=9533;
 update phrases set phrase_text='That’s alright' where id=9534;
 update phrases set phrase_text='That’s enough' where id=9535;
 update phrases set phrase_text='That’s fair' where id=9536;
 update phrases set phrase_text='That’s fine' where id=9537;
 update phrases set phrase_text='That’s good' where id=9538;
 update phrases set phrase_text='That’s great!' where id=9539;
 update phrases set phrase_text='That’s her book' where id=9540;
 update phrases set phrase_text='That’s it' where id=9541;
 update phrases set phrase_text='That smells bad' where id=9542;
 update phrases set phrase_text='That’s not enough'where id=9543;
 update phrases set phrase_text='That’s not fair' where id=9544;
 update phrases set phrase_text='That’s not right' where id=9545;
 update phrases set phrase_text='That’s right' where id=9546;
 update phrases set phrase_text='That’s too bad' where id=9547;
 update phrases set phrase_text='That’s too expensive' where id=9548;
 update phrases set phrase_text='That’s too late' where id=9549;
 update phrases set phrase_text='That’s too many' where id=9550;
 update phrases set phrase_text='That’s too much' where id=9551;
 update phrases set phrase_text='That’s wrong' where id=9552;
 update phrases set phrase_text='That way' where id=9553;
 update phrases set phrase_text='The accident happened at the intersection' where id=9554;
 update phrases set phrase_text='The big one or the small one' where id=9555;
 update phrases set phrase_text='The book is behind the table' where id=9556;
 update phrases set phrase_text='The book is in front of the table'where id=9557;
 update phrases set phrase_text='The book is near the table' where id=9558;
 update phrases set phrase_text='The books are expensive' where id=9559;
 update phrases set phrase_text='The car is fixed' where id=9560;
 update phrases set phrase_text='The cars are American' where id=9561;
 update phrases set phrase_text='The food was delicious' where id=9562;
 update phrases set phrase_text='The plane departs at530' where id=9563;
 update phrases set phrase_text='There are many people here' where id=9564;
 update phrases set phrase_text='There are some apples in the refrigerator' where id=9565;
 update phrases set phrase_text='There are some books on the table'where id=9566;
 update phrases set phrase_text='There has been a car accident' where id=9567;
 update phrases set phrase_text='There’s a book under the table' where id=9568;
 update phrases set phrase_text='There’s a restaurant near here' where id=9569;
 update phrases set phrase_text='There’s a restaurant over there but I don’t think its very good' where id=9570;
 update phrases set phrase_text='There’s plenty of time' where id=9571;
 update phrases set phrase_text='The roads are slippery' where id=9572;
 update phrases set phrase_text='These books are ours' where id=9573;
 update phrases set phrase_text='The TV is broken' where id=9574;
 update phrases set phrase_text='The whole day' where id=9575;
 update phrases set phrase_text='They arrived yesterday' where id=9576;
 update phrases set phrase_text='They charge twenty six dollars per day' where id=9577;
 update phrases set phrase_text='They haven’t met her yet' where id=9578;
 update phrases set phrase_text='They’ll be right back' where id=9579;
 update phrases set phrase_text='They’re planning to come next year' where id=9580;
 update phrases set phrase_text='They’re the same' where id=9581;
 update phrases set phrase_text='They’re very busy'where id=9582;
 update phrases set phrase_text='They’re waiting for us' where id=9583;
 update phrases set phrase_text='This doesn’t work'where id=9584;
 update phrases set phrase_text='This house is very big' where id=9585;
 update phrases set phrase_text='This is Mrs. Smith' where id=9586;
 update phrases set phrase_text='This is my mother'where id=9587;
 update phrases set phrase_text='This is the first time I’ve been here' where id=9588;
 update phrases set phrase_text='This is very difficult' where id=9589;
 update phrases set phrase_text='This is very important' where id=9590;
 update phrases set phrase_text='This room is a mess' where id=9591;
 update phrases set phrase_text='Those men are speaking English' where id=9592;
 update phrases set phrase_text='Try it' where id=9593;
 update phrases set phrase_text='Try it on' where id=9594;
 update phrases set phrase_text='Try to say it' where id=9595;
 update phrases set phrase_text='Turn around' where id=9596;
 update phrases set phrase_text='Turn left' where id=9597;
 update phrases set phrase_text='Turn right' where id=9598;
 update phrases set phrase_text='Very good, thanks' where id=9599;
 update phrases set phrase_text='Waiter' where id=9600;
 update phrases set phrase_text='Waitress' where id=9601;
 update phrases set phrase_text='We can eat Italian or Chinese food' where id=9602;
 update phrases set phrase_text='We have two boys and one girl' where id=9603;
 update phrases set phrase_text='We like it very much' where id=9604;
 update phrases set phrase_text='We’ll have two glasses of water please' where id=9605;
 update phrases set phrase_text='We’re from california' where id=9606;
 update phrases set phrase_text='We’re late' where id=9607;
 update phrases set phrase_text='Were there any problems?' where id=9608;
 update phrases set phrase_text='Were you at the library last night?' where id=9609;
 update phrases set phrase_text='What are you doing?' where id=9610;
 update phrases set phrase_text='What are you going to do tonight?'where id=9611;
 update phrases set phrase_text='What are you going to have?' where id=9612;
 update phrases set phrase_text='What are your hobbies?' where id=9613;
 update phrases set phrase_text='What are you thinking about?' where id=9614;
 update phrases set phrase_text='What are you two talking about?' where id=9615;
 update phrases set phrase_text='What can I do for you?' where id=9616;
 update phrases set phrase_text='What color is that car?' where id=9617;
 update phrases set phrase_text='What day are they coming over?' where id=9618;
 update phrases set phrase_text='What day of the week is it?' where id=9619;
 update phrases set phrase_text='What did you do last night?' where id=9620;
 update phrases set phrase_text='What did you do yesterday?' where id=9621;
 update phrases set phrase_text='What did you think?' where id=9622;
 update phrases set phrase_text='What does he do for work?' where id=9623;
 update phrases set phrase_text='What does this mean?' where id=9624;
 update phrases set phrase_text='What does this say?' where id=9625;
 update phrases set phrase_text='What does this word mean?' where id=9626;
 update phrases set phrase_text='What does your father do for work?' where id=9627;
 update phrases set phrase_text='What do people usually do in the summer in Los Angeles?' where id=9628;
 update phrases set phrase_text='What do they study?' where id=9629;
 update phrases set phrase_text='What do you do for work?' where id=9630;
 update phrases set phrase_text='What do you have?'where id=9631;
 update phrases set phrase_text='What do you recommend?' where id=9632;
 update phrases set phrase_text='What do your parents do for work?'where id=9633;
 update phrases set phrase_text='What do you study?' where id=9634;
 update phrases set phrase_text='What do you think?' where id=9635;
 update phrases set phrase_text='What do you think of these shoes?'where id=9636;
 update phrases set phrase_text='What to you want?'where id=9637;
 update phrases set phrase_text='What do you want to buy?' where id=9638;
 update phrases set phrase_text='What do you want to do?' where id=9639;
 update phrases set phrase_text='What happened?' where id=9640;
 update phrases set phrase_text='What is it?' where id=9641;
 update phrases set phrase_text='What is that?' where id=9642;
 update phrases set phrase_text='What is the area code?' where id=9643;
 update phrases set phrase_text='What is todays date?' where id=9644;
 update phrases set phrase_text='What kind of music do you like?' where id=9645;
 update phrases set phrase_text='What school did you go to?' where id=9646;
 update phrases set phrase_text='What should I wear?' where id=9647;
 update phrases set phrase_text='Whats in it?' where id=9648;
 update phrases set phrase_text='What size?' where id=9649;
 update phrases set phrase_text='What’s the address?' where id=9650;
 update phrases set phrase_text='What’s the charge per night?' where id=9651;
 update phrases set phrase_text='What’s the date?' where id=9652;
 update phrases set phrase_text='What’s the exchange rate?' where id=9653;
 update phrases set phrase_text='What’s the exchange rate for dollars?' where id=9654;
 update phrases set phrase_text='What’s the matter?' where id=9655;
 update phrases set phrase_text='What’s the name of the company you work for?' where id=9656;
 update phrases set phrase_text='What’s the phone number?' where id=9657;
 update phrases set phrase_text='What’s the room rate?' where id=9658;
 update phrases set phrase_text='What’s the temperature?' where id=9659;
 update phrases set phrase_text='What’s this?' where id=9660;
 update phrases set phrase_text='What’s todays date?' where id=9661;
 update phrases set phrase_text='What’s up?' where id=9662;
 update phrases set phrase_text='What’s wrong?' where id=9663;
 update phrases set phrase_text='What’s your address?' where id=9664;
 update phrases set phrase_text='What’s your favorite food?' where id=9665;
 update phrases set phrase_text='What’s your favorite movie?' where id=9666;
 update phrases set phrase_text='What’s your last name?' where id=9667;
 update phrases set phrase_text='What’s your name?'where id=9668;
 update phrases set phrase_text='What’s your religion?' where id=9669;
 update phrases set phrase_text='What time are they arriving?' where id=9670;
 update phrases set phrase_text='What time are you going to the bus station?' where id=9671;
 update phrases set phrase_text='What time did you get up?' where id=9672;
 update phrases set phrase_text='What time did you go to sleep?' where id=9673;
 update phrases set phrase_text='What time did you wake up?' where id=9674;
 update phrases set phrase_text='What time does it start?' where id=9675;
 update phrases set phrase_text='What time does the movie start?' where id=9676;
 update phrases set phrase_text='What time does the store open?' where id=9677;
 update phrases set phrase_text='What time do you go to work everyday?' where id=9678;
 update phrases set phrase_text='What time do you think youll arrive?' where id=9679;
 update phrases set phrase_text='What time is checkout?' where id=9680;
 update phrases set phrase_text='What time is it?' where id=9681;
 update phrases set phrase_text='What will the weather be like tomorrow?' where id=9682;
 update phrases set phrase_text='What would you like to drink?' where id=9683;
 update phrases set phrase_text='What would you like to eat?' where id=9684;
 update phrases set phrase_text='When are they coming?' where id=9685;
 update phrases set phrase_text='When are you coming back?' where id=9686;
 update phrases set phrase_text='When are you going to pick up your friend?' where id=9687;
 update phrases set phrase_text='When are you leaving?' where id=9688;
 update phrases set phrase_text='When are you moving?' where id=9689;
 update phrases set phrase_text='When did this happen?' where id=9690;
 update phrases set phrase_text='When did you arrive in Boston?' where id=9691;
 update phrases set phrase_text='When does he arrive?' where id=9692;
 update phrases set phrase_text='When does it arrive?' where id=9693;
 update phrases set phrase_text='When does it leave?' where id=9694;
 update phrases set phrase_text='When does the bank open?' where id=9695;
 update phrases set phrase_text='When does the bus leave?' where id=9696;
 update phrases set phrase_text='When does the plane arrive?' where id=9697;
 update phrases set phrase_text='When do we arrive?' where id=9698;
 update phrases set phrase_text='When do you arrive in the United States?' where id=9699;
 update phrases set phrase_text='When do you get off work?' where id=9700;
 update phrases set phrase_text='When is the next bus to Philadelphia?' where id=9701;
 update phrases set phrase_text='When is your birthday?' where id=9702;
 update phrases set phrase_text='When I went to the store they didn’t have any apples?' where id=9703;
 update phrases set phrase_text='When will it be ready?' where id=9704;
 update phrases set phrase_text='When would you like to meet?' where id=9705;
 update phrases set phrase_text='Where are the t-shirts?' where id=9706;
 update phrases set phrase_text='Where are you?' where id=9707;
 update phrases set phrase_text='Where are you from?' where id=9708;
 update phrases set phrase_text='Where are you going?' where id=9709;
 update phrases set phrase_text='Where are you going to go?' where id=9710;
 update phrases set phrase_text='Where can I buy tickets?' where id=9711;
 update phrases set phrase_text='Where can I exchange US dollars?' where id=9712;
 update phrases set phrase_text='Where can I find a hospital?' where id=9713;
 update phrases set phrase_text='Where can I mail this?' where id=9714;
 update phrases set phrase_text='Where can I rent a car?' where id=9715;
 update phrases set phrase_text='Where did it happen?' where id=9716;
 update phrases set phrase_text='Where did you go?'where id=9717;
 update phrases set phrase_text='Where did you learn English?' where id=9718;
 update phrases set phrase_text='Where did you learn it?' where id=9719;
 update phrases set phrase_text='Where did you put it?' where id=9720;
 update phrases set phrase_text='Where did you work before you worked here?' where id=9721;
 update phrases set phrase_text='Where does it hurt?' where id=9722;
 update phrases set phrase_text='Where does your wife work?' where id=9723;
 update phrases set phrase_text='Where do you live?' where id=9724;
 update phrases set phrase_text='Where do you wantto go?' where id=9725;
 update phrases set phrase_text='Where do you work?' where id=9726;
 update phrases set phrase_text='Where is he?' where id=9727;
 update phrases set phrase_text='Where is he from?'where id=9728;
 update phrases set phrase_text='Where is it?' where id=9729;
 update phrases set phrase_text='Where is Main street?' where id=9730;
 update phrases set phrase_text='Where is my shirt?' where id=9731;
 update phrases set phrase_text='Where is she from?' where id=9732;
 update phrases set phrase_text='Where is the airport?' where id=9733;
 update phrases set phrase_text='Where is the bathroom?' where id=9734;
 update phrases set phrase_text='Where is the bus station?' where id=9735;
 update phrases set phrase_text='Where is there a doctor who speaks English?' where id=9736;
 update phrases set phrase_text='Where is there an ATM?' where id=9737;
 update phrases set phrase_text='Where’s the closest restaurant?' where id=9738;
 update phrases set phrase_text='Where’s the mail box?' where id=9739;
 update phrases set phrase_text='Where’s the nearest hospital?' where id=9740;
 update phrases set phrase_text='Where’s the pharmacy?' where id=9741;
 update phrases set phrase_text='Where’s the post office?' where id=9742;
 update phrases set phrase_text='Where were you?' where id=9743;
 update phrases set phrase_text='Where would you like to go?' where id=9744;
 update phrases set phrase_text='Where would you like to meet?' where id=9745;
 update phrases set phrase_text='Which is better?' where id=9746;
 update phrases set phrase_text='Which is better the spaghetti or chicken salad?' where id=9747;
 update phrases set phrase_text='Which is the best?' where id=9748;
 update phrases set phrase_text='Which one?' where id=9749;
 update phrases set phrase_text='Which one do you want?' where id=9750;
 update phrases set phrase_text='Which one is better?' where id=9751;
 update phrases set phrase_text='Which one is cheaper?' where id=9752;
 update phrases set phrase_text='Which one is the best?' where id=9753;
 update phrases set phrase_text='Which road should I take?' where id=9754;
 update phrases set phrase_text='Which school does he go to?' where id=9755;
 update phrases set phrase_text='Who are they?' where id=9756;
 update phrases set phrase_text='Who is it?' where id=9757;
 update phrases set phrase_text='Who is that?' where id=9758;
 update phrases set phrase_text='Who’s book is that?' where id=9759;
 update phrases set phrase_text='Who sent this letter?' where id=9760;
 update phrases set phrase_text='Who’s that man over there?' where id=9761;
 update phrases set phrase_text='Who taught you?' where id=9762;
 update phrases set phrase_text='Who taught you that?' where id=9763;
 update phrases set phrase_text='Who was that?' where id=9764;
 update phrases set phrase_text='Who was your teacher?' where id=9765;
 update phrases set phrase_text='Who won?' where id=9766;
 update phrases set phrase_text='Who would you like to speak to?' where id=9767;
 update phrases set phrase_text='Why arent you going?' where id=9768;
 update phrases set phrase_text='Why are you laughing?' where id=9769;
 update phrases set phrase_text='Why did you do that?' where id=9770;
 update phrases set phrase_text='Why did you say that?' where id=9771;
 update phrases set phrase_text='Why not?' where id=9772;
 update phrases set phrase_text='Will you call me a taxi please?' where id=9773;
 update phrases set phrase_text='Will you hand me a towel please?' where id=9774;
 update phrases set phrase_text='Will you pass me the salt please?'where id=9775;
 update phrases set phrase_text='Will you put this in the car for me?' where id=9776;
 update phrases set phrase_text='Will you remind me?' where id=9777;
 update phrases set phrase_text='Will you take me home?' where id=9778;
 update phrases set phrase_text='Would you ask him to call me back please?' where id=9779;
 update phrases set phrase_text='Would you ask him to come here?' where id=9780;
 update phrases set phrase_text='Would you like a glass of water?' where id=9781;
 update phrases set phrase_text='Would you like coffee or tea?' where id=9782;
 update phrases set phrase_text='Would you like something to drink?' where id=9783;
 update phrases set phrase_text='Would you like something to eat?' where id=9784;
 update phrases set phrase_text='Would you like some water?' where id=9785;
 update phrases set phrase_text='Would you like some wine?' where id=9786;
 update phrases set phrase_text='Would you like to buy this?' where id=9787;
 update phrases set phrase_text='Would you like to go for a walk?' where id=9788;
 update phrases set phrase_text='Would you like to have dinner with me?' where id=9789;
 update phrases set phrase_text='Would you like to rent a movie?' where id=9790;
 update phrases set phrase_text='Would you like to watch TV?' where id=9791;
 update phrases set phrase_text='Would you like water or milk?' where id=9792;
 update phrases set phrase_text='Would you take a message please?' where id=9793;
 update phrases set phrase_text='Yes really' where id=9794;
 update phrases set phrase_text='Yes' where id=9795;
 update phrases set phrase_text='You have a very nice car' where id=9796;
 update phrases set phrase_text='You look great!' where id=9797;
 update phrases set phrase_text='You look like my sister' where id=9798;
 update phrases set phrase_text='You look tired' where id=9799;
 update phrases set phrase_text='Your children are very well behaved' where id=9800;
 update phrases set phrase_text='Your daughter' where id=9801;
 update phrases set phrase_text='You’re beautiful' where id=9802;
 update phrases set phrase_text='You’re right' where id=9803;
 update phrases set phrase_text='You’re smarter than him' where id=9804;
 update phrases set phrase_text='You’re very nice' where id=9805;
 update phrases set phrase_text='You’re very smart'where id=9806;
 update phrases set phrase_text='You’re welcome' where id=9807;
 update phrases set phrase_text='Your house is very nice' where id=9808;
 update phrases set phrase_text='Your things are all here' where id=9809;
 update phrases set phrase_text='You speak English very well' where id=9810;
