update phrases set phrase_text='à environ 300 kilomètres' where id=18667;
update phrases set phrase_text='en face du bureau de poste' where id=18668;
update phrases set phrase_text='quelques' where id=18669;
update phrases set phrase_text='un peu' where id=18670;
update phrases set phrase_text='toute la journée' where id=18671;
update phrases set phrase_text='il y a longtemps' where id=18672;
update phrases set phrase_text='Est-ce que je prononce correctement ?' where id=18673;
update phrases set phrase_text='Amy est la petite amie de Johns' where id=18674;
update phrases set phrase_text='et vous ?' where id=18675;
update phrases set phrase_text='rien d’autre' where id=18676;
update phrases set phrase_text='un billet aller simple' where id=18677;
update phrases set phrase_text='y at-il des concerts ?' where id=18678;
update phrases set phrase_text='viennent-ils ce soir ?' where id=18679;
update phrases set phrase_text='sont-ils les mêmes ?' where id=18680;
update phrases set phrase_text='avez-vous peur ?' where id=18681;
update phrases set phrase_text='Avez-vous des allergies ?' where id=18682;
update phrases set phrase_text='Êtes-vous américain ?' where id=18683;
update phrases set phrase_text='Êtes-vous occupé ?' where id=18684;
update phrases set phrase_text='Êtes-vous à l’aise ?' where id=18685;
update phrases set phrase_text='Venez-vous ce soir ?' where id=18686;
update phrases set phrase_text='Êtes-vous libre ce soir ?' where id=18687;
update phrases set phrase_text='Serez-vous présent à leur mariage ?' where id=18688;
update phrases set phrase_text='Allez-vous l’aider ?' where id=18689;
update phrases set phrase_text='Allez-vous prendre l’avion ?' where id=18690;
update phrases set phrase_text='Êtes-vous seul ?' where id=18691;
update phrases set phrase_text='Avez-vous faim ?' where id=18692;
update phrases set phrase_text='Êtes-vous marié ?' where id=18693;
update phrases set phrase_text='Vous allez bien ?' where id=18694;
update phrases set phrase_text='Vos enfants sont-ils avec vous ?' where id=18695;
update phrases set phrase_text='Êtes-vous prêt ?' where id=18696;
update phrases set phrase_text='Êtes-vous malade ?' where id=18697;
update phrases set phrase_text='Êtes-vous sûr ?' where id=18698;
update phrases set phrase_text='Attendez-vous quelqu’un ?' where id=18699;
update phrases set phrase_text='Travaillez-vous aujourd’hui ?' where id=18700;
update phrases set phrase_text='Travaillez-vous demain ?' where id=18701;
update phrases set phrase_text='un billet aller-retour' where id=18702;
update phrases set phrase_text='dès que possible' where id=18703;
update phrases set phrase_text='à 3 heures' where id=18704;
update phrases set phrase_text='à 15 heures' where id=18705;
update phrases set phrase_text='dans la 5ème rue' where id=18706;
update phrases set phrase_text='à 7 heures du soir' where id=18707;
update phrases set phrase_text='à quelle heure' where id=18708;
update phrases set phrase_text='à quel moment est-ce arrivé' where id=18709;
update phrases set phrase_text='faites attention' where id=18710;
update phrases set phrase_text='Soyez prudent en conduisant' where id=18711;
update phrases set phrase_text='derrière la banque' where id=18712;
update phrases set phrase_text='soyez silencieux' where id=18713;
update phrases set phrase_text='apportez-moi ma chemise s’il vous plaît' where id=18714;
update phrases set phrase_text='les affaires sont bonnes' where id=18715;
update phrases set phrase_text='appelez-moi' where id=18716;
update phrases set phrase_text='appelez la police' where id=18717;
update phrases set phrase_text='Puis-je accéder à Internet ici ?' where id=18718;
update phrases set phrase_text='Puis-je emprunter de l’argent ?' where id=18719;
update phrases set phrase_text='Puis-je venir avec un ami ?' where id=18720;
update phrases set phrase_text='Puis-je avoir un verre d’eau s’il vous plaît ?' where id=18721;
update phrases set phrase_text='Puis-je avoir un reçu s’il vous plaît ?' where id=18722;
update phrases set phrase_text='Puis-je avoir le projet de loi s’il vous plaît ?' where id=18723;
update phrases set phrase_text='Puis-je vous aider ?' where id=18724;
update phrases set phrase_text='Puis-je prendre rendez-vous pour mercredi prochain ?' where id=18725;
update phrases set phrase_text='Puis-je voir votre passeport s’il vous plaît ?' where id=18726;
update phrases set phrase_text='Puis-je prendre un message ?' where id=18727;
update phrases set phrase_text='Cela peut-il être moins cher ?' where id=18728;
update phrases set phrase_text='Puis-je l’essayer ?' where id=18729;
update phrases set phrase_text='Puis-je utiliser votre téléphone ?' where id=18730;
update phrases set phrase_text='Pouvons-nous avoir un menu s’il vous plaît ?' where id=18731;
update phrases set phrase_text='Pouvons-nous avoir un peu plus de pain s’il vous plaît ?' where id=18732;
update phrases set phrase_text='Pouvons-nous nous asseoir là-bas ?' where id=18733;
update phrases set phrase_text='Pouvez-vous rappeler plus tard ?' where id=18734;
update phrases set phrase_text='Pouvez-vous porter ceci pour moi ?' where id=18735;
update phrases set phrase_text='Pouvez-vous me rendre service ?' where id=18736;
update phrases set phrase_text='Pouvez-vous réparer ceci ?' where id=18737;
update phrases set phrase_text='Pouvez-vous me donner un exemple ?' where id=18738;
update phrases set phrase_text='Pouvez-vous m’aider ?' where id=18739;
update phrases set phrase_text='Pouvez-vous tenir ceci pour moi ?' where id=18740;
update phrases set phrase_text='Pouvez-vous m’aider s’il vous plaît ?' where id=18741;
update phrases set phrase_text='Pouvez-vous répéter s’il vous plaît ?' where id=18742;
update phrases set phrase_text='Avez-vous un bon restaurant à recommander ?' where id=18743;
update phrases set phrase_text='Pouvez vous répéter s’il vous plaît ?' where id=18744;
update phrases set phrase_text='Pouvez-vous me montrer ?' where id=18745;
update phrases set phrase_text='Pouvez-vous parler plus fort s’il vous plaît ?' where id=18746;
update phrases set phrase_text='Savez-vous nager ?' where id=18747;
update phrases set phrase_text='Pouvez-vous jeter ça pour moi ?' where id=18748;
update phrases set phrase_text='Vous pouvez traduire ceci pour moi ?' where id=18749;
update phrases set phrase_text='sûrement' where id=18750;
update phrases set phrase_text='santé' where id=18751;
update phrases set phrase_text='Chicago est très différent de Boston' where id=18752;
update phrases set phrase_text='venez ici' where id=18753;
update phrases set phrase_text='A-t-il neigé hier ?' where id=18754;
update phrases set phrase_text='Êtes-vous venu avec votre famille ?' where id=18755;
update phrases set phrase_text='Avez-vous reçu mon email ?' where id=18756;
update phrases set phrase_text='Votre femme a-t-elle aimé la Californie ?' where id=18757;
update phrases set phrase_text='M’avez-vous envoyé des fleurs ?' where id=18758;
update phrases set phrase_text='Avez-vous pris votre médicament ?' where id=18759;
update phrases set phrase_text='Est-ce que quelqu’un parle anglais ici ?' where id=18760;
update phrases set phrase_text='il n’aime l’école ?' where id=18761;
update phrases set phrase_text='Neige-t-il souvent en hiver dans le Massachusetts ?' where id=18762;
update phrases set phrase_text='Cette route mène-t-elle à New York ?' where id=18763;
update phrases set phrase_text='Ne faites pas cela.' where id=18764;
update phrases set phrase_text='Ne vous inquiétez pas.' where id=18765;
update phrases set phrase_text='Acceptez-vous les dollars américains ?' where id=18766;
update phrases set phrase_text='Vous le croyez ?' where id=18767;
update phrases set phrase_text='Vous sentez-vous mieux ?' where id=18768;
update phrases set phrase_text='Allez-vous souvent en Floride ?' where id=18769;
update phrases set phrase_text='Avez-vous un petit ami ?' where id=18770;
update phrases set phrase_text='Avez-vous une petite amie ?' where id=18771;
update phrases set phrase_text='Avez-vous un rendez-vous ?' where id=18772;
update phrases set phrase_text='Avez-vous quelqu’un dans la vie ?' where id=18773;
update phrases set phrase_text='Avez-vous des enfants ?' where id=18774;
update phrases set phrase_text='Auriez-vous du café ?' where id=18775;
update phrases set phrase_text='Auriez-vous de l’argent ?' where id=18776;
update phrases set phrase_text='Avez-vous quelque chose de moins cher ?' where id=18777;
update phrases set phrase_text='Avez-vous des postes vacants ?' where id=18778;
update phrases set phrase_text='Auriez-vous un crayon ?' where id=18779;
update phrases set phrase_text='Avez-vous un problème ?' where id=18780;
update phrases set phrase_text='Avez-vous une piscine ?' where id=18781;
update phrases set phrase_text='Avez-vous assez d’argent ?' where id=18782;
update phrases set phrase_text='Avez-vous le numéro pour un taxi ?' where id=18783;
update phrases set phrase_text='Avez-vous ceci en taille 11 ?' where id=18784;
update phrases set phrase_text='Entendez-vous ?' where id=18785;
update phrases set phrase_text='ne savez-lui que vous ?' where id=18786;
update phrases set phrase_text='savez-vous combien il en coûte ?' where id=18787;
update phrases set phrase_text='savez-vous comment faire cuire ?' where id=18788;
update phrases set phrase_text='savez-vous comment se rendre à l’hôtel de Marriott ?' where id=18789;
update phrases set phrase_text='savez-vous ce que cela signifie ?' where id=18790;
update phrases set phrase_text='savez-vous ce que cela dit ?' where id=18791;
update phrases set phrase_text='savez-vous où je peux prendre un taxi ?' where id=18792;
update phrases set phrase_text='savez-vous où sont mes lunettes ?' where id=18793;
update phrases set phrase_text='savez-vous où elle est ?' where id=18794;
update phrases set phrase_text='savez-vous où theres un magasin qui vend des serviettes ?' where id=18795;
update phrases set phrase_text='aimez-vous ici ?' where id=18796;
update phrases set phrase_text='vous aimez le livre ?' where id=18797;
update phrases set phrase_text='aimez-vous regarder t v ?' where id=18798;
update phrases set phrase_text='Aimez-vous votre patron ?' where id=18799;
update phrases set phrase_text='aimez-vous vos collègues ?' where id=18800;
update phrases set phrase_text='avez-vous besoin de quelque chose ?' where id=18801;
update phrases set phrase_text='-vous besoin d’autre chose ?' where id=18802;
update phrases set phrase_text='ne jouez-vous du sport ?' where id=18803;
update phrases set phrase_text='-vous jouer au basket ?' where id=18804;
update phrases set phrase_text='vendez-vous des piles ?' where id=18805;
update phrases set phrase_text='vendez-vous la médecine ?' where id=18806;
update phrases set phrase_text='fumez-vous ?' where id=18807;
update phrases set phrase_text='parlez-vous anglais ?' where id=18808;
update phrases set phrase_text='ne étudiez-vous anglais ?' where id=18809;
update phrases set phrase_text='prenez-vous les cartes de crédit ?' where id=18810;
update phrases set phrase_text='pensez-vous qu’il va pleuvoir aujourd’hui ?' where id=18811;
update phrases set phrase_text='pensez-vous que sa va pleuvoir aujourd’hui ?' where id=18812;
update phrases set phrase_text='pensez-vous de sa possible ?' where id=18813;
update phrases set phrase_text='pensez-vous que vous aurez sera de retour en 1130 ?' where id=18814;
update phrases set phrase_text='comprenez vous ?' where id=18815;
update phrases set phrase_text='voulez-vous que je vienne vous chercher ?' where id=18816;
update phrases set phrase_text='voulez-vous venir avec moi ?' where id=18817;
update phrases set phrase_text='voulez-vous aller au cinéma ?' where id=18818;
update phrases set phrase_text='voulez-vous venir avec moi ?' where id=18819;
update phrases set phrase_text='tous les jours je me lève à six' where id=18820;
update phrases set phrase_text='tout le monde le sait' where id=18821;
update phrases set phrase_text='tout est prêt' where id=18822;
update phrases set phrase_text='chaque semaine' where id=18823;
update phrases set phrase_text='excellent' where id=18824;
update phrases set phrase_text='excusez-moi' where id=18825;
update phrases set phrase_text='excusez-moi qu’est-ce que vous dites' where id=18826;
update phrases set phrase_text='date d’expiration' where id=18827;
update phrases set phrase_text='le remplir s’il vous plaît' where id=18828;
update phrases set phrase_text='suivez-moi' where id=18829;
update phrases set phrase_text='oublie' where id=18830;
update phrases set phrase_text='combien de nuits' where id=18831;
update phrases set phrase_text='d’ici à là' where id=18832;
update phrases set phrase_text='de temps en temps' where id=18833;
update phrases set phrase_text='Fuck that!' where id=18834;
update phrases set phrase_text='me donner un appel' where id=18835;
update phrases set phrase_text='me donner la plume' where id=18836;
update phrases set phrase_text='bon après-midi' where id=18837;
update phrases set phrase_text='Bonsoir Monsieur' where id=18838;
update phrases set phrase_text='bonne idée' where id=18839;
update phrases set phrase_text='bonne chance' where id=18840;
update phrases set phrase_text='bonjour' where id=18841;
update phrases set phrase_text='aller tout droit' where id=18842;
update phrases set phrase_text='grand' where id=18843;
update phrases set phrase_text='joyeux anniversaire' where id=18844;
update phrases set phrase_text='a ton frère connaissez California' where id=18845;
update phrases set phrase_text='avoir un bon voyage' where id=18846;
update phrases set phrase_text='ont-ils l’ont rencontrée encore ?' where id=18847;
update phrases set phrase_text='êtes-vous arrivé ?' where id=18848;
update phrases set phrase_text='avez-vous été à Boston ?' where id=18849;
update phrases set phrase_text='avez-vous été longue attente ?' where id=18850;
update phrases set phrase_text='avez-vous fait cela avant ?' where id=18851;
update phrases set phrase_text='avez-vous mangé dans ce restaurant ?' where id=18852;
update phrases set phrase_text='avez-vous encore mangé ?' where id=18853;
update phrases set phrase_text='avez-vous déjà eu la soupe de pommes de terre ?' where id=18854;
update phrases set phrase_text='avez-vous terminé vos études ?' where id=18855;
update phrases set phrase_text='avez-vous vu ce film ?' where id=18856;
update phrases set phrase_text='il le fait toujours pour moi' where id=18857;
update phrases set phrase_text= 'bruyère' where id=18858;
update phrases set phrase_text='il a cassé la fenêtre' where id=18859;
update phrases set phrase_text='il ne ressemble pas à une infirmière' where id=18860;
update phrases set phrase_text='il a une belle voiture' where id=18861;
update phrases set phrase_text='il l’aime beaucoup' where id=18862;
update phrases set phrase_text='il aime le jus, mais il ne aime pas le lait' where id=18863;
update phrases set phrase_text='l’enfer de retour en vingt minutes' where id=18864;
update phrases set phrase_text='bonjour' where id=18865;
update phrases set phrase_text='aidez-moi' where id=18866;
update phrases set phrase_text='il a besoin de nouveaux vêtements' where id=18867;
update phrases set phrase_text='il ne m’a jamais donne rien' where id=18868;
update phrases set phrase_text='c’est ici' where id=18869;
update phrases set phrase_text='voici mon numéro' where id=18870;
update phrases set phrase_text='voici votre commande' where id=18871;
update phrases set phrase_text='voici votre salade' where id=18872;
update phrases set phrase_text='vous voilà' where id=18873;
update phrases set phrase_text='il dit que ce est un endroit agréable' where id=18874;
update phrases set phrase_text='il a dit que vous aimez regarder des films' where id=18875;
update phrases set phrase_text='il est un Américain' where id=18876;
update phrases set phrase_text='il est un ingénieur' where id=18877;
update phrases set phrase_text='ce est un très bon élève' where id=18878;
update phrases set phrase_text='il est pour bientôt' where id=18879;
update phrases set phrase_text='il est plus rapide que moi' where id=18880;
update phrases set phrase_text='il est dans la cuisine' where id=18881;
update phrases set phrase_text='il n’a jamais été en Amérique' where id=18882;
update phrases set phrase_text='il ne est pas en ce moment' where id=18883;
update phrases set phrase_text='il a raison' where id=18884;
update phrases set phrase_text='il étudie à l’Université de Boston' where id=18885;
update phrases set phrase_text='il est très ennuyeux' where id=18886;
update phrases set phrase_text='il est très célèbre' where id=18887;
update phrases set phrase_text='Il est très travaillant dur' where id=18888;
update phrases set phrase_text='il pense que nous ne voulons pas aller' where id=18889;
update phrases set phrase_text='Il travaille dans une société d’informatique à New York' where id=18890;
update phrases set phrase_text='salut est Mme Smith il s’il vous plaît' where id=18891;
update phrases set phrase_text='sa famille est pour demain' where id=18892;
update phrases set phrase_text='sa chambre est très petite' where id=18893;
update phrases set phrase_text='son fils' where id=18894;
update phrases set phrase_text='que diriez-vous samedi ?' where id=18895;
update phrases set phrase_text='comment allez-vous ?' where id=18896;
update phrases set phrase_text='comment allez-vous payer ?' where id=18897;
update phrases set phrase_text='comment sont vos parents ?' where id=18898;
update phrases set phrase_text='quel est son goût ?' where id=18899;
update phrases set phrase_text='comment puis-je y arriver ?' where id=18900;
update phrases set phrase_text='comment puis-je obtenir à la rue Daniel ?' where id=18901;
update phrases set phrase_text='comment puis-je obtenir à l’ambassade américaine ?' where id=18902;
update phrases set phrase_text='comment puis-je l’utiliser ?' where id=18903;
update phrases set phrase_text='comment savez-vous ?' where id=18904;
update phrases set phrase_text='comment prononcez-vous cela ?' where id=18905;
update phrases set phrase_text='comment dit-on en anglais ?' where id=18906;
update phrases set phrase_text='comment ça s’épelle ?' where id=18907;
update phrases set phrase_text='Comment épelez-vous le mot Seattle ?' where id=18908;
update phrases set phrase_text='dans quelle mesure est-il ?' where id=18909;
update phrases set phrase_text='dans quelle mesure est-il à Chicago ?' where id=18910;
update phrases set phrase_text='comment est-elle ?' where id=18911;
update phrases set phrase_text='combien de temps allez-vous rester ?' where id=18912;
update phrases set phrase_text='combien de temps allez-vous rester en Californie ?' where id=18913;
update phrases set phrase_text='combien de temps cela prend-il en voiture ?' where id=18914;
update phrases set phrase_text='combien de temps faut-il pour obtenir à la Géorgie ?' where id=18915;
update phrases set phrase_text='combien de temps êtes-vous ici ?' where id=18916;
update phrases set phrase_text='combien de temps avez-vous travaillé ici ?' where id=18917;
update phrases set phrase_text='combien de temps est-il ?' where id=18918;
update phrases set phrase_text='combien de temps dure le vol ?' where id=18919;
update phrases set phrase_text='combien de temps ça va prendre ?' where id=18920;
update phrases set phrase_text='combien de temps resterez-vous ?' where id=18921;
update phrases set phrase_text='combien ?' where id=18922;
update phrases set phrase_text='combien d’enfants avez-vous ?' where id=18923;
update phrases set phrase_text='combien d’heures par semaine travaillez-vous ?' where id=18924;
update phrases set phrase_text='Combien de langues parlez-vous ?' where id=18925;
update phrases set phrase_text='combien de miles est-il en Pennsylvanie ?' where id=18926;
update phrases set phrase_text='combien de personnes ?' where id=18927;
update phrases set phrase_text='combien de personnes sont là à New York ?' where id=18928;
update phrases set phrase_text='combien de personnes avez-vous dans votre famille ?' where id=18929;
update phrases set phrase_text='combien tout ensemble ?' where id=18930;
update phrases set phrase_text='combien sont ces boucles d’oreilles ?' where id=18931;
update phrases set phrase_text='combien ça coûte par jour ?' where id=18932;
update phrases set phrase_text='Combien ça coûte ?' where id=18933;
update phrases set phrase_text='combien vous dois-je ?' where id=18934;
update phrases set phrase_text='combien ça coûte ?' where id=18935;
update phrases set phrase_text='combien est-il pour aller à Miami ?' where id=18936;
update phrases set phrase_text='Combien est-ce ?' where id=18937;
update phrases set phrase_text='combien ça coûte ?' where id=18938;
update phrases set phrase_text='combien d’argent avez-vous ?' where id=18939;
update phrases set phrase_text='combien d’argent faites-vous ?' where id=18940;
update phrases set phrase_text='combien ça coûtera ?' where id=18941;
update phrases set phrase_text='Combien seriez-vous ?' where id=18942;
update phrases set phrase_text='quel âge avez-vous ?' where id=18943;
update phrases set phrase_text='Comment vont les affaires ?' where id=18944;
update phrases set phrase_text='comment est la météo ?' where id=18945;
update phrases set phrase_text='comment ça travaux en cours ?' where id=18946;
update phrases set phrase_text='quelle est votre taille ?' where id=18947;
update phrases set phrase_text='Comment était le film ?' where id=18948;
update phrases set phrase_text='comment était le voyage ?' where id=18949;
update phrases set phrase_text='se dépêcher' where id=18950;
update phrases set phrase_text='je suis d’accord' where id=18951;
update phrases set phrase_text='Je ai mangé déjà' where id=18952;
update phrases set phrase_text='Je te crois' where id=18953;
update phrases set phrase_text='Je ai acheté une chemise hier' where id=18954;
update phrases set phrase_text='Je suis venu avec ma famille' where id=18955;
update phrases set phrase_text='Je peux nager' where id=18956;
update phrases set phrase_text='Je ne vous entends pas' where id=18957;
update phrases set phrase_text='Je ne peux pas vous entendre clairement' where id=18958;
update phrases set phrase_text='Je aimerais une carte de la ville' where id=18959;
update phrases set phrase_text='Je voudrais une chambre non-fumeurs' where id=18960;
update phrases set phrase_text='Je voudrais une chambre' where id=18961;
update phrases set phrase_text='Je voudrais une chambre avec deux lits s’il vous plaît' where id=18962;
update phrases set phrase_text='Je voudrais une chambre simple' where id=18963;
update phrases set phrase_text='Je aimerais une table près de la fenêtre' where id=18964;
update phrases set phrase_text='Je aimerais un peu d’eau trop s’il vous plaît' where id=18965;
update phrases set phrase_text='Je voudrais le numéro de l’hôtel Hilton s’il vous plaît' where id=18966;
update phrases set phrase_text='Je aimerais acheter une bouteille d’eau s’il vous plaît' where id=18967;
update phrases set phrase_text='Je aimerais acheter une carte de téléphone s’il vous plaît' where id=18968;
update phrases set phrase_text='Je aimerais acheter quelque chose' where id=18969;
update phrases set phrase_text='Je aimerais appeler les Etats-Unis' where id=18970;
update phrases set phrase_text='Je aimerais manger au restaurant au cinquième rue' where id=18971;
update phrases set phrase_text='Je aimerais l’échanger contre de dollars' where id=18972;
update phrases set phrase_text='Je aimerais aller pour une promenade' where id=18973;
update phrases set phrase_text='Je aimerais rentrer à la maison' where id=18974;
update phrases set phrase_text='Je aimerais aller faire du shopping' where id=18975;
update phrases set phrase_text='Je aimerais aller au magasin' where id=18976;
update phrases set phrase_text='Je aimerais faire un appel téléphonique' where id=18977;
update phrases set phrase_text='Je aimerais faire une réservation' where id=18978;
update phrases set phrase_text='Je aimerais louer une voiture' where id=18979;
update phrases set phrase_text='Je aimerais envoyer un fax' where id=18980;
update phrases set phrase_text='Je voudrais l’envoyer à l’Amérique' where id=18981;
update phrases set phrase_text='Je aimerais parler à M. Smith s’il vous plaît' where id=18982;
update phrases set phrase_text='Je aimerais utiliser l’Internet' where id=18983;
update phrases set phrase_text='Je ne m’inquiète pas' where id=18984;
update phrases set phrase_text='Je ne me sens pas bien' where id=18985;
update phrases set phrase_text='Je ne ai pas une petite amie' where id=18986;
update phrases set phrase_text='Je ne ai pas d’argent' where id=18987;
update phrases set phrase_text='Je ne ai pas le temps maintenant' where id=18988;
update phrases set phrase_text='Je ne sais pas' where id=18989;
update phrases set phrase_text='Je ne sais pas comment l’utiliser' where id=18990;
update phrases set phrase_text='Je ne l’aime pas' where id=18991;
update phrases set phrase_text='Je ne l’aime pas' where id=18992;
update phrases set phrase_text='Cela ne me dérange pas' where id=18993;
update phrases set phrase_text='Je ne parle pas très bien anglais' where id=18994;
update phrases set phrase_text='Je ne parle pas très bien' where id=18995;
update phrases set phrase_text='Je ne pense pas' where id=18996;
update phrases set phrase_text='Je ne comprends pas' where id=18997;
update phrases set phrase_text='Je ne comprends pas ce que votre disant' where id=18998;
update phrases set phrase_text='Je ne veux pas' where id=18999;
update phrases set phrase_text='Je ne veux pas que' where id=19000;
update phrases set phrase_text='Je ne veux pas vous déranger' where id=19001;
update phrases set phrase_text='Je me sens bien' where id=19002;
update phrases set phrase_text='je oublie' where id=19003;
update phrases set phrase_text='si vous aimez je peux acheter plus' where id=19004;
update phrases set phrase_text='si vous avez besoin de mon aide s’il vous plaît laissez-moi savoir' where id=19005;
update phrases set phrase_text='Je descends à travailler à six' where id=19006;
update phrases set phrase_text='J’abandonne' where id=19007;
update phrases set phrase_text='Je ai eu dans un accident' where id=19008;
update phrases set phrase_text='J’ai un rhume' where id=19009;
update phrases set phrase_text='J’ai mal à la tête' where id=19010;
update phrases set phrase_text='Je ai beaucoup de choses à faire' where id=19011;
update phrases set phrase_text='Je ai une question que je veux vous poser' where id=19012;
update phrases set phrase_text='J’ai une réservation' where id=19013;
update phrases set phrase_text='Je ai de l’argent' where id=19014;
update phrases set phrase_text='Je ne ai pas été là' where id=19015;
update phrases set phrase_text='Je ne ai pas fini de manger' where id=19016;
update phrases set phrase_text='Je ne ai pas encore eu le déjeuner' where id=19017;
update phrases set phrase_text='Je ai une dans ma voiture' where id=19018;
update phrases set phrase_text='Je ai une douleur dans mon bras' where id=19019;
update phrases set phrase_text='Je ai trois enfants deux filles et un garçon' where id=19020;
update phrases set phrase_text='Je dois aller au bureau de poste' where id=19021;
update phrases set phrase_text='Je dois laver mes vêtements' where id=19022;
update phrases set phrase_text='Je ai deux sœurs' where id=19023;
update phrases set phrase_text='Je espère que vous et votre épouse avez un beau voyage' where id=19024;
update phrases set phrase_text='je sais' where id=19025;
update phrases set phrase_text='Je l’aime' where id=19026;
update phrases set phrase_text='Je l’aime' where id=19027;
update phrases set phrase_text='Je aime la cuisine italienne' where id=19028;
update phrases set phrase_text='Je aime regarder la télévision' where id=19029;
update phrases set phrase_text='Je vis en Californie' where id=19030;
update phrases set phrase_text='Je serai bientôt de retour' where id=19031;
update phrases set phrase_text='Je rappelle plus tard' where id=19032;
update phrases set phrase_text='Je te appellerai le vendredi' where id=19033;
update phrases set phrase_text='Je vous appellerai quand je quitte' where id=19034;
update phrases set phrase_text='Je reviendrai plus tard' where id=19035;
update phrases set phrase_text='Je vais vous donner un appel' where id=19036;
update phrases set phrase_text='Je ai une tasse de thé s’il vous plaît' where id=19037;
update phrases set phrase_text='Je vais prendre un verre d’eau s’il vous plaît' where id=19038;
update phrases set phrase_text='Je prendrai la même chose' where id=19039;
update phrases set phrase_text='Je paierai' where id=19040;
update phrases set phrase_text='Je vais payer pour le dîner' where id=19041;
update phrases set phrase_text='Je vais payer pour les billets' where id=19042;
update phrases set phrase_text='Je le prends' where id=19043;
update phrases set phrase_text='Je prends ça une aussi' where id=19044;
update phrases set phrase_text='Je vais vous conduire à l’arrêt de bus' where id=19045;
update phrases set phrase_text='Je vais vous parler bientôt' where id=19046;
update phrases set phrase_text='Je vous apprendrai' where id=19047;
update phrases set phrase_text='Je lui dirai que vous avez appelé' where id=19048;
update phrases set phrase_text='Je ai perdu ma montre' where id=19049;
update phrases set phrase_text='Je te aime' where id=19050;
update phrases set phrase_text='Je suis un débutant' where id=19051;
update phrases set phrase_text='Je ai fait une erreur' where id=19052;
update phrases set phrase_text='Je ai fait ce gâteau' where id=19053;
update phrases set phrase_text='Je suis allergique aux fruits de mer' where id=19054;
update phrases set phrase_text='Je suis Américain' where id=19055;
update phrases set phrase_text='Je suis un Américain' where id=19056;
update phrases set phrase_text='Je suis une taille de huit' where id=19057;
update phrases set phrase_text='Je suis un enseignant' where id=19058;
update phrases set phrase_text='Je m’ennuie' where id=19059;
update phrases set phrase_text='Je nettoie ma chambre' where id=19060;
update phrases set phrase_text='J’ai froid' where id=19061;
update phrases set phrase_text='Je viens en ce moment' where id=19062;
update phrases set phrase_text='Je viens vous chercher' where id=19063;
update phrases set phrase_text='Je vais bien et vous' where id=19064;
update phrases set phrase_text='Je suis d’Amérique' where id=19065;
update phrases set phrase_text='Je suis plein' where id=19066;
update phrases set phrase_text='Je me prépare à sortir' where id=19067;
update phrases set phrase_text='Je vais à la maison en quatre jours' where id=19068;
update phrases set phrase_text='Je vais amérique année prochaine' where id=19069;
update phrases set phrase_text='Je vais au lit' where id=19070;
update phrases set phrase_text='Je vais aller dîner' where id=19071;
update phrases set phrase_text='Je vais quitter' where id=19072;
update phrases set phrase_text='Je suis bon' where id=19073;
update phrases set phrase_text='Je suis bon et vous' where id=19074;
update phrases set phrase_text='Je suis heureux' where id=19075;
update phrases set phrase_text='Je suis ici pour affaires' where id=19076;
update phrases set phrase_text='Je suis chaud' where id=19077;
update phrases set phrase_text='J’ai faim' where id=19078;
update phrases set phrase_text='C’est juste une plaisanterie' where id=19079;
update phrases set phrase_text='Je cherche juste' where id=19080;
update phrases set phrase_text='Je pars demain' where id=19081;
update phrases set phrase_text='Je suis à la recherche pour le bureau de poste' where id=19082;
update phrases set phrase_text='Je suis perdu' where id=19083;
update phrases set phrase_text='Je suis marié' where id=19084;
update phrases set phrase_text='Je n’ai pas peur' where id=19085;
update phrases set phrase_text='Je ne suis pas américain' where id=19086;
update phrases set phrase_text='Je ne suis pas occupé' where id=19087;
update phrases set phrase_text='Je ne vais pas' where id=19088;
update phrases set phrase_text='Je ne suis pas marié' where id=19089;
update phrases set phrase_text='Je ne suis pas encore prêt' where id=19090;
update phrases set phrase_text='Je ne suis pas sûr' where id=19091;
update phrases set phrase_text='Je vais bien' where id=19092;
update phrases set phrase_text='Je suis en attente' where id=19093;
update phrases set phrase_text='Je suis prêt' where id=19094;
update phrases set phrase_text='Je Indépendant' where id=19095;
update phrases set phrase_text='Je suis malade' where id=19096;
update phrases set phrase_text='Je suis célibataire' where id=19097;
update phrases set phrase_text='Je suis six pieds deux' where id=19098;
update phrases set phrase_text='Je suis désolé' where id=19099;
update phrases set phrase_text='Je suis désolé que nous vendions sur' where id=19100;
update phrases set phrase_text='J’ai soif' where id=19101;
update phrases set phrase_text='Je suis trente-deux' where id=19102;
update phrases set phrase_text='Je suis fatigué' where id=19103;
update phrases set phrase_text='Je suis âgé de 26 années' where id=19104;
update phrases set phrase_text='Je suis très occupé' where id=19105;
update phrases set phrase_text='Je suis très occupé, je ne ai pas le temps maintenant' where id=19106;
update phrases set phrase_text='Je suis très bien merci' where id=19107;
update phrases set phrase_text='Je vous attends' where id=19108;
update phrases set phrase_text='Je suis inquiet trop' where id=19109;
update phrases set phrase_text='Je ai besoin d’un médecin' where id=19110;
update phrases set phrase_text='Je ai besoin d’une autre touche' where id=19111;
update phrases set phrase_text='Je ai besoin de certains tissus' where id=19112;
update phrases set phrase_text='Je en ai besoin pour y arriver d’ici demain' where id=19113;
update phrases set phrase_text='Je ai besoin de changer de vêtements' where id=19114;
update phrases set phrase_text='Je ai besoin de rentrer à la maison' where id=19115;
update phrases set phrase_text='Je dois y aller maintenant' where id=19116;
update phrases set phrase_text='Je ai besoin d’aller au lit' where id=19117;
update phrases set phrase_text='Je ai besoin d’aller à la salle de bains' where id=19118;
update phrases set phrase_text='Je ai besoin de pratiquer mon anglais' where id=19119;
update phrases set phrase_text='en trente minutes' where id=19120;
update phrases set phrase_text='Je ne ai que cinq dollars' where id=19121;
update phrases set phrase_text='Je veux seulement une collation' where id=19122;
update phrases set phrase_text='je me souviens' where id=19123;
update phrases set phrase_text='est quelqu’un d’autre arrive ?' where id=19124;
update phrases set phrase_text='tout est OK ?' where id=19125;
update phrases set phrase_text='est-il à proximité ?' where id=19126;
update phrases set phrase_text='est-il froid dehors ?' where id=19127;
update phrases set phrase_text='est-ce loin d ’ici ?' where id=19128;
update phrases set phrase_text='est-ce que c’est chaud ?' where id=19129;
update phrases set phrase_text='est-il à proximité ?' where id=19130;
update phrases set phrase_text='est-il possible ?' where id=19131;
update phrases set phrase_text='est-ce qu’il pleut ?' where id=19132;
update phrases set phrase_text='est-elle prête ?' where id=19133;
update phrases set phrase_text='est-il censé pleuvoir demain ?' where id=19134;
update phrases set phrase_text='John est ici ?' where id=19135;
update phrases set phrase_text='John est là s’il vous plaît ?' where id=19136;
update phrases set phrase_text='M. Smith est un Américain ?' where id=19137;
update phrases set phrase_text='n’est-ce pas ?' where id=19138;
update phrases set phrase_text='Je parle un peu l’anglais' where id=19139;
update phrases set phrase_text='Je parle deux langues' where id=19140;
update phrases set phrase_text='est-ce suffisant ?' where id=19141;
update phrases set phrase_text='est que OK ?' where id=19142;
update phrases set phrase_text='est l’autre rive ?' where id=19143;
update phrases set phrase_text='est-il l’air conditionné dans la chambre ?' where id=19144;
update phrases set phrase_text='y at-il une salle de cinéma à proximité ?' where id=19145;
update phrases set phrase_text='il est un guide anglophone ?' where id=19146;
update phrases set phrase_text='il est un club de nuit en ville ?' where id=19147;
update phrases set phrase_text='y a t-il un message pour moi ?' where id=19148;
update phrases set phrase_text='y a-t-il quelque chose de moins cher ?' where id=19149;
update phrases set phrase_text='est-il un restaurant dans l’hôtel ?' where id=19150;
update phrases set phrase_text='est-il un magasin près d’ici ?' where id=19151;
update phrases set phrase_text='est-ce une zone de sécurité ?' where id=19152;
update phrases set phrase_text='est-ce M. Smith ?' where id=19153;
update phrases set phrase_text='ce stylo est le vôtre ?' where id=19154;
update phrases set phrase_text='ce est le bus à New York ?' where id=19155;
update phrases set phrase_text='est-ce votre livre ?' where id=19156;
update phrases set phrase_text='Je ai encore beaucoup de choses à acheter' where id=19157;
update phrases set phrase_text='Je ai encore beaucoup de travail à faire' where id=19158;
update phrases set phrase_text='Je nai pas encore décidé' where id=19159;
update phrases set phrase_text='Je ai encore à me brosser les dents et prendre une douche' where id=19160;
update phrases set phrase_text='est votre père à la maison ?' where id=19161;
update phrases set phrase_text='est votre maison comme celle-ci ?' where id=19162;
update phrases set phrase_text='votre mari est également de Boston ?' where id=19163;
update phrases set phrase_text='est votre fils ici ?' where id=19164;
update phrases set phrase_text='il en coûte vingt dollars par heure' where id=19165;
update phrases set phrase_text='cela dépend de la météo' where id=19166;
update phrases set phrase_text='Je pense que je ai besoin de voir un médecin' where id=19167;
update phrases set phrase_text='Je pense que sa très bonne' where id=19168;
update phrases set phrase_text='Je pense que ce est bon' where id=19169;
update phrases set phrase_text='Je pense que oui' where id=19170;
update phrases set phrase_text='Je pense que ces chaussures sont très beau' where id=19171;
update phrases set phrase_text='Je pense que vous avez trop de vêtements' where id=19172;
update phrases set phrase_text='Je pensais qu’il avait dit quelque chose d’autre' where id=19173;
update phrases set phrase_text='Je pensais que les vêtements étaient moins cher' where id=19174;
update phrases set phrase_text='c’est douloureux ici' where id=19175;
update phrases set phrase_text='ça va être froid ce soir' where id=19176;
update phrases set phrase_text='il a plu très fort aujourd’hui' where id=19177;
update phrases set phrase_text='Je compte sur toi' where id=19178;
update phrases set phrase_text='ce est Août vingt-cinquième' where id=19179;
update phrases set phrase_text='ce est délicieux' where id=19180;
update phrases set phrase_text='il est huit quarante-cinq' where id=19181;
update phrases set phrase_text='ce est 1130' where id=19182;
update phrases set phrase_text='ce est loin d’ici' where id=19183;
update phrases set phrase_text='ça va être chaud aujourd’hui' where id=19184;
update phrases set phrase_text='il va de neige aujourd’hui' where id=19185;
update phrases set phrase_text='ce est moitié onze dernières' where id=19186;
update phrases set phrase_text='ce est ici' where id=19187;
update phrases set phrase_text='ce est moins de cinq dollars' where id=19188;
update phrases set phrase_text='ce est plus de deux miles' where id=19189;
update phrases set phrase_text='ce est le mien' where id=19190;
update phrases set phrase_text='ce est plus de cinq dollars' where id=19191;
update phrases set phrase_text='ce est près du supermarché' where id=19192;
update phrases set phrase_text='ce est au nord d’ici' where id=19193;
update phrases set phrase_text='il ne est pas censé pleuvoir aujourd’hui' where id=19194;
update phrases set phrase_text='ce n’est pas très loin' where id=19195;
update phrases set phrase_text='ce ne est pas très coûteux' where id=19196;
update phrases set phrase_text='c’est OK' where id=19197;
update phrases set phrase_text='ce est sur Seventh Street' where id=19198;
update phrases set phrase_text='ce est là-bas' where id=19199;
update phrases set phrase_text='il est neuf heures et quart' where id=19200;
update phrases set phrase_text='ce est sept heures moins le quart' where id=19201;
update phrases set phrase_text='il pleut' where id=19202;
update phrases set phrase_text='ce est vraiment chaud' where id=19203;
update phrases set phrase_text='ce est dix-sept dollars' where id=19204;
update phrases set phrase_text='elle est plus courte de trois miles' where id=19205;
update phrases set phrase_text='il est six' where id=19206;
update phrases set phrase_text='il est censé pleuvoir demain' where id=19207;
update phrases set phrase_text='ce est là' where id=19208;
update phrases set phrase_text='il est trop tard' where id=19209;
update phrases set phrase_text='il fait très froid aujourd’hui' where id=19210;
update phrases set phrase_text='il est très important' where id=19211;
update phrases set phrase_text='ce est très venteux' where id=19212;
update phrases set phrase_text='il faut deux heures en voiture' where id=19213;
update phrases set phrase_text='il arrivera peu de temps' where id=19214;
update phrases set phrase_text='je comprends' where id=19215;
update phrases set phrase_text='Je comprends maintenant' where id=19216;
update phrases set phrase_text='Je ai l’habitude de boire du café au petit déjeuner' where id=19217;
update phrases set phrase_text='Je ai déjà vu ça' where id=19218;
update phrases set phrase_text='Je ai été ici pendant deux jours' where id=19219;
update phrases set phrase_text='Je ai été là' where id=19220;
update phrases set phrase_text='Je ai entendu au Texas, est un bel endroit' where id=19221;
update phrases set phrase_text='Je ne ai jamais fait ça' where id=19222;
update phrases set phrase_text='Je ne ai jamais vu ça avant' where id=19223;
update phrases set phrase_text='Je l’ai vu' where id=19224;
update phrases set phrase_text='J’y ai travaillé pendant cinq ans' where id=19225;
update phrases set phrase_text='Je veux acheter quelque chose' where id=19226;
update phrases set phrase_text='Je veux contacter notre ambassade' where id=19227;
update phrases set phrase_text='Je veux vous donner un cadeau' where id=19228;
update phrases set phrase_text='Je veux envoyer ce paquet aux États-Unis' where id=19229;
update phrases set phrase_text='Je veux vous montrer quelque chose' where id=19230;
update phrases set phrase_text='Je étais sur le point de quitter le restaurant quand mes amis sont arrivés' where id=19231;
update phrases set phrase_text='Je allais à la bibliothèque' where id=19232;
update phrases set phrase_text='Je étais dans la bibliothèque' where id=19233;
update phrases set phrase_text='Je suis allé au supermarché et puis au magasin d’informatique' where id=19234;
update phrases set phrase_text='Je voudrais avoir une' where id=19235;
update phrases set phrase_text='John va en vacances demain' where id=19236;
update phrases set phrase_text='Judy' where id=19237;
update phrases set phrase_text='Julianne' where id=19238;
update phrases set phrase_text='troisième Juin' where id=19239;
update phrases set phrase_text='juste un peu' where id=19240;
update phrases set phrase_text='juste un moment' where id=19241;
update phrases set phrase_text='laissez-moi vérifier' where id=19242;
update phrases set phrase_text='Let Me Think About It' where id=19243;
update phrases set phrase_text='Mangeons' where id=19244;
update phrases set phrase_text='allons-y' where id=19245;
update phrases set phrase_text='Allons jeter un oeil' where id=19246;
update phrases set phrase_text='nous allons rencontrer en face de l’hôtel' where id=19247;
update phrases set phrase_text='nous allons pratiquer l’anglais' where id=19248;
update phrases set phrase_text='nous allons partager' where id=19249;
update phrases set phrase_text='masculin ou féminin' where id=19250;
update phrases set phrase_text='peut être' where id=19251;
update phrases set phrase_text='puis-je parler à Mme Smith s’il vous plaît' where id=19252;
update phrases set phrase_text='plus que' where id=19253;
update phrases set phrase_text='plus de deux cents miles' where id=19254;
update phrases set phrase_text='Mon anniversaire est Vingtième Août' where id=19255;
update phrases set phrase_text='ma voiture ne fonctionne pas' where id=19256;
update phrases set phrase_text='ma voiture a été heurtée par une autre voiture' where id=19257;
update phrases set phrase_text='mon téléphone portable ne marche pas avoir une bonne réception' where id=19258;
update phrases set phrase_text='mon téléphone portable ne fonctionne pas' where id=19259;
update phrases set phrase_text='ma fille est ici' where id=19260;
update phrases set phrase_text='mon père a été là' where id=19261;
update phrases set phrase_text='mon père est un avocat' where id=19262;
update phrases set phrase_text='mon ami est américain' where id=19263;
update phrases set phrase_text='ma grand-mère est décédée l’année dernière' where id=19264;
update phrases set phrase_text='ma maison est proche de la banque' where id=19265;
update phrases set phrase_text='mes bagages est manquant' where id=19266;
update phrases set phrase_text='mon nom est John Smith' where id=19267;
update phrases set phrase_text='mon fils' where id=19268;
update phrases set phrase_text='mon fils étudie ordinateurs' where id=19269;
update phrases set phrase_text='mon estomac fait mal' where id=19270;
update phrases set phrase_text='mon mal à la gorge' where id=19271;
update phrases set phrase_text='ma montre a été volée' where id=19272;
update phrases set phrase_text='près de la rive' where id=19273;
update phrases set phrase_text='ça ne fait rien' where id=19274;
update phrases set phrase_text='la prochaine fois' where id=19275;
update phrases set phrase_text='ravi de vous rencontrer' where id=19276;
update phrases set phrase_text='non, je suis américain' where id=19277;
update phrases set phrase_text='non, ce est la première fois' where id=19278;
update phrases set phrase_text= 'aucun' where id=19279;
update phrases set phrase_text='personne ne nous aide' where id=19280;
update phrases set phrase_text='personne ne est là en ce moment' where id=19281;
update phrases set phrase_text='non-sens' where id=19282;
update phrases set phrase_text='pas de problème' where id=19283;
update phrases set phrase_text='non merci' where id=19284;
update phrases set phrase_text='rien d’autre' where id=19285;
update phrases set phrase_text='pas récemment' where id=19286;
update phrases set phrase_text='pas encore' where id=19287;
update phrases set phrase_text='maintenant' where id=19288;
update phrases set phrase_text='maintenant ou plus tard' where id=19289;
update phrases set phrase_text='octobre vingt secondes' where id=19290;
update phrases set phrase_text='bien sûr' where id=19291;
update phrases set phrase_text='d’accord' where id=19292;
update phrases set phrase_text='un comme ça' where id=19293;
update phrases set phrase_text='un billet pour New York, s’il vous plaît' where id=19294;
update phrases set phrase_text='une manière ou aller-retour' where id=19295;
update phrases set phrase_text='sur la gauche' where id=19296;
update phrases set phrase_text='sur la droite' where id=19297;
update phrases set phrase_text='sur thesecond chaussée' where id=19298;
update phrases set phrase_text='ouvrir la porte' where id=19299;
update phrases set phrase_text='ouvrir la fenêtre' where id=19300;
update phrases set phrase_text='nos enfants sont en Amérique' where id=19301;
update phrases set phrase_text='extérieur de l’hôtel' where id=19302;
update phrases set phrase_text='ici' where id=19303;
update phrases set phrase_text='là-bas' where id=19304;
update phrases set phrase_text='ramassage vos vêtements' where id=19305;
update phrases set phrase_text='s’il vous plaît' where id=19306;
update phrases set phrase_text='s’il vous plaît appelez-moi' where id=19307;
update phrases set phrase_text='s’il vous plaît venir' where id=19308;
update phrases set phrase_text='s’il vous plaît compter pour moi' where id=19309;
update phrases set phrase_text='s’il vous plaît remplir ce formulaire' where id=19310;
update phrases set phrase_text='Se il vous plaît me aider ?' where id=19311;
update phrases set phrase_text='s’il vous plaît asseoir' where id=19312;
update phrases set phrase_text='s’il vous plaît parler anglais' where id=19313;
update phrases set phrase_text='s’il vous plaît parler plus lentement' where id=19314;
update phrases set phrase_text='s’il vous plaît parler plus lentement' where id=19315;
update phrases set phrase_text='s’il vous plaît me prendre à l’aéroport' where id=19316;
update phrases set phrase_text='s’il vous plaît prenez-moi à cette adresse' where id=19317;
update phrases set phrase_text='s’il vous plaît enlever vos chaussures' where id=19318;
update phrases set phrase_text='s’il vous plaît dites-lui appelé John' where id=19319;
update phrases set phrase_text='s’il vous plaît dites-moi' where id=19320;
update phrases set phrase_text='s’il vous plaît me attendre' where id=19321;
update phrases set phrase_text='s’il vous plaît écrivez-' where id=19322;
update phrases set phrase_text='vraiment' where id=19323;
update phrases set phrase_text='ici' where id=19324;
update phrases set phrase_text='là' where id=19325;
update phrases set phrase_text='Sarah' where id=19326;
update phrases set phrase_text='à plus tard' where id=19327;
update phrases set phrase_text='à demain' where id=19328;
update phrases set phrase_text='vous voir ce soir' where id=19329;
update phrases set phrase_text='elle est un expert' where id=19330;
update phrases set phrase_text='elle va avec moi demain' where id=19331;
update phrases set phrase_text='elle est plus âgé que moi' where id=19332;
update phrases set phrase_text='elle est jolie' where id=19333;
update phrases set phrase_text='elle veut savoir quand votre venue' where id=19334;
update phrases set phrase_text='dois-je attendre' where id=19335;
update phrases set phrase_text='des livres' where id=19336;
update phrases set phrase_text='quelqu’un fait cela pour moi' where id=19337;
update phrases set phrase_text='quelqu’un vient' where id=19338;
update phrases set phrase_text='parfois je vais dormir à onze parfois à 1130' where id=19339;
update phrases set phrase_text='désolé, je ne ai pas entendu clairement' where id=19340;
update phrases set phrase_text='désolé, je ne ai pas un crayon' where id=19341;
update phrases set phrase_text='désolé, je pense que je ai le mauvais numéro' where id=19342;
update phrases set phrase_text='désolé de vous déranger' where id=19343;
update phrases set phrase_text='Désolé, nous ne acceptons pas les cartes de crédit' where id=19344;
update phrases set phrase_text='Désolé, nous ne avons pas' where id=19345;
update phrases set phrase_text='Désolé, nous ne avons pas de postes vacants' where id=19346;
update phrases set phrase_text='désolé, nous acceptons uniquement les espèces' where id=19347;
update phrases set phrase_text='démarrer la voiture' where id=19348;
update phrases set phrase_text='arrêtez' where id=19349;
update phrases set phrase_text='prendre une chance' where id=19350;
update phrases set phrase_text='prendre à l’extérieur' where id=19351;
update phrases set phrase_text='me prendre le centre-ville' where id=19352;
update phrases set phrase_text='me prendre à l’hôtel de Marriott' where id=19353;
update phrases set phrase_text='prendre ce médicament' where id=19354;
update phrases set phrase_text='lui dire que je ai besoin de lui parler' where id=19355;
update phrases set phrase_text='dîtes-moi' where id=19356;
update phrases set phrase_text='merci' where id=19357;
update phrases set phrase_text='merci pour tout' where id=19358;
update phrases set phrase_text='merci pour votre aide' where id=19359;
update phrases set phrase_text='merci' where id=19360;
update phrases set phrase_text='merci manquer' where id=19361;
update phrases set phrase_text='merci monsieur' where id=19362;
update phrases set phrase_text='merci beaucoup' where id=19363;
update phrases set phrase_text='C’est bon' where id=19364;
update phrases set phrase_text='C’est génial' where id=19365;
update phrases set phrase_text='cette voiture est similaire à ma voiture' where id=19366;
update phrases set phrase_text='cette voiture là-bas est le mien' where id=19367;
update phrases set phrase_text='qui ressemble beaucoup' where id=19368;
update phrases set phrase_text='qui ressemble ancienne' where id=19369;
update phrases set phrase_text='cela signifie ami' where id=19370;
update phrases set phrase_text='ce restaurant ne est pas cher' where id=19371;
update phrases set phrase_text='ce est une bonne école' where id=19372;
update phrases set phrase_text='ce est bien' where id=19373;
update phrases set phrase_text='ça suffit' where id=19374;
update phrases set phrase_text='que ce est juste' where id=19375;
update phrases set phrase_text='c’est très bien' where id=19376;
update phrases set phrase_text='ce est son livre' where id=19377;
update phrases set phrase_text='c’est tout' where id=19378;
update phrases set phrase_text='qui sent mauvais' where id=19379;
update phrases set phrase_text='cela ne suffit pas' where id=19380;
update phrases set phrase_text='ce est pas juste' where id=19381;
update phrases set phrase_text='ce ne est pas droit' where id=19382;
update phrases set phrase_text='c’est ça' where id=19383;
update phrases set phrase_text='ce est dommage' where id=19384;
update phrases set phrase_text='ce est trop cher' where id=19385;
update phrases set phrase_text='ce est trop tard' where id=19386;
update phrases set phrase_text='ce est trop' where id=19387;
update phrases set phrase_text='ce est trop' where id=19388;
update phrases set phrase_text='ce est faux' where id=19389;
update phrases set phrase_text='de cette façon' where id=19390;
update phrases set phrase_text='l’accident se est produit à l’intersection' where id=19391;
update phrases set phrase_text='le grand ou le petit' where id=19392;
update phrases set phrase_text='le livre est derrière la table' where id=19393;
update phrases set phrase_text='le livre est en face de la table' where id=19394;
update phrases set phrase_text='le livre est près de la table' where id=19395;
update phrases set phrase_text='les livres sont chers' where id=19396;
update phrases set phrase_text='la voiture est fixe' where id=19397;
update phrases set phrase_text='les voitures sont américain' where id=19398;
update phrases set phrase_text='la nourriture était délicieuse' where id=19399;
update phrases set phrase_text='l’avion se écarte at530' where id=19400;
update phrases set phrase_text='il ya beaucoup de gens ici' where id=19401;
update phrases set phrase_text='il ya des pommes dans le réfrigérateur' where id=19402;
update phrases set phrase_text='il ya des livres sur la table' where id=19403;
update phrases set phrase_text='il ya eu un accident de voiture' where id=19404;
update phrases set phrase_text='il ya un livre sous la table' where id=19405;
update phrases set phrase_text='il ya un restaurant près d’ici' where id=19406;
update phrases set phrase_text='il ya un restaurant là-bas mais je ne pense pas que sa très bonne' where id=19407;
update phrases set phrase_text='il ya beaucoup de temps' where id=19408;
update phrases set phrase_text='les routes sont glissantes' where id=19409;
update phrases set phrase_text='ces livres sont les nôtres' where id=19410;
update phrases set phrase_text='le téléviseur est cassé' where id=19411;
update phrases set phrase_text='toute la journée' where id=19412;
update phrases set phrase_text='ils sont arrivés hier' where id=19413;
update phrases set phrase_text='ils chargent vingt-six dollars par jour' where id=19414;
update phrases set phrase_text='ils ne ont pas encore rencontrée' where id=19415;
update phrases set phrase_text='ils seront de retour' where id=19416;
update phrases set phrase_text='ils ont l’intention de venir l’année prochaine' where id=19417;
update phrases set phrase_text='ce est la même' where id=19418;
update phrases set phrase_text='ils sont très occupés' where id=19419;
update phrases set phrase_text='ils attendent pour nous' where id=19420;
update phrases set phrase_text='cela ne fonctionne pas' where id=19421;
update phrases set phrase_text='cette maison est très grand' where id=19422;
update phrases set phrase_text='ce est Mme Smith' where id=19423;
update phrases set phrase_text='ce est ma mère' where id=19424;
update phrases set phrase_text='ce est la première fois que je ai été ici' where id=19425;
update phrases set phrase_text='cela est très difficile' where id=19426;
update phrases set phrase_text='ceci est très important' where id=19427;
update phrases set phrase_text='cette salle est un gâchis' where id=19428;
update phrases set phrase_text='ces hommes sont anglophones' where id=19429;
update phrases set phrase_text='essayer' where id=19430;
update phrases set phrase_text='essayer sur' where id=19431;
update phrases set phrase_text='essayer de le dire' where id=19432;
update phrases set phrase_text='faire demi-tour' where id=19433;
update phrases set phrase_text='tourner à gauche' where id=19434;
update phrases set phrase_text='tournez à droite' where id=19435;
update phrases set phrase_text='très bonne grâce' where id=19436;
update phrases set phrase_text='garçon' where id=19437;
update phrases set phrase_text='serveuse' where id=19438;
update phrases set phrase_text='nous pouvons manger de la nourriture italienne ou chinoise' where id=19439;
update phrases set phrase_text='nous avons deux garçons et une fille' where id=19440;
update phrases set phrase_text='nous aimons très beaucoup' where id=19441;
update phrases set phrase_text='nous aurons deux verres d’eau s’il vous plaît' where id=19442;
update phrases set phrase_text='nous sommes de Californie' where id=19443;
update phrases set phrase_text='nous sommes en retard' where id=19444;
update phrases set phrase_text='avait-il des problèmes ?' where id=19445;
update phrases set phrase_text='vous étiez à la bibliothèque la nuit dernière ?' where id=19446;
update phrases set phrase_text='que faites-vous ?' where id=19447;
update phrases set phrase_text='qu’allez-vous faire ce soir ?' where id=19448;
update phrases set phrase_text='qu’allez-vous avoir ?' where id=19449;
update phrases set phrase_text='Quels sont vos hobbies ?' where id=19450;
update phrases set phrase_text='qu’est-ce que tu penses ?' where id=19451;
update phrases set phrase_text='qu’est-ce que vous parlez de deux ?' where id=19452;
update phrases set phrase_text='que puis-je faire pour vous ?' where id=19453;
update phrases set phrase_text='de quelle couleur est cette voiture ?' where id=19454;
update phrases set phrase_text='ce jour viennent-ils plus ?' where id=19455;
update phrases set phrase_text='quel jour de la semaine est-il ?' where id=19456;
update phrases set phrase_text='qu’avez-vous fait hier soir ?' where id=19457;
update phrases set phrase_text='qu’avez-vous fait hier ?' where id=19458;
update phrases set phrase_text='qu’avez-vous pensé ?' where id=19459;
update phrases set phrase_text='que fait-il pour le travail ?' where id=19460;
update phrases set phrase_text='qu’est-ce que cela signifie ?' where id=19461;
update phrases set phrase_text='qu’est-ce que cela nous dit ?' where id=19462;
update phrases set phrase_text='qu’est-ce que ce mot veut dire ?' where id=19463;
update phrases set phrase_text='qu’est-ce que votre père pour le travail ?' where id=19464;
update phrases set phrase_text='que font les gens habituellement dans l’été à Los Angeles ?' where id=19465;
update phrases set phrase_text='ce étudient-ils ?' where id=19466;
update phrases set phrase_text='que faites-vous pour le travail ?' where id=19467;
update phrases set phrase_text='qu’est-ce que vous avez ?' where id=19468;
update phrases set phrase_text='que recommandez-vous ?' where id=19469;
update phrases set phrase_text='ce font vos parents pour le travail ?' where id=19470;
update phrases set phrase_text='qu’est-ce que tu étudies ?' where id=19471;
update phrases set phrase_text='que pensez-vous ?' where id=19472;
update phrases set phrase_text='que pensez-vous de ces chaussures ?' where id=19473;
update phrases set phrase_text='Qu’est-ce que vous voulez ?' where id=19474;
update phrases set phrase_text='que voulez-vous acheter ?' where id=19475;
update phrases set phrase_text='qu’est-ce que vous voulez faire ?' where id=19476;
update phrases set phrase_text='ce qui s’est passé ?' where id=19477;
update phrases set phrase_text='qu’est-ce que c’est ?' where id=19478;
update phrases set phrase_text='qu’est-ce que c’est ?' where id=19479;
update phrases set phrase_text='ce est l’indicatif régional ?' where id=19480;
update phrases set phrase_text='ce est la date du jour ?' where id=19481;
update phrases set phrase_text='quel genre de musique aimez-vous ?' where id=19482;
update phrases set phrase_text='quelle école êtes-vous allé ?' where id=19483;
update phrases set phrase_text='que dois-je porter ?' where id=19484;
update phrases set phrase_text='ce qui est en elle ?' where id=19485;
update phrases set phrase_text='quelle taille ?' where id=19486;
update phrases set phrase_text='Quelle est l’adresse ?' where id=19487;
update phrases set phrase_text='ce est la charge par nuit ?' where id=19488;
update phrases set phrase_text='ce est la date ?' where id=19489;
update phrases set phrase_text='quel est le taux de change ?' where id=19490;
update phrases set phrase_text='quel est le taux de change du dollar ?' where id=19491;
update phrases set phrase_text='quel est le problème ?' where id=19492;
update phrases set phrase_text='quel est le nom de l’entreprise pour laquelle vous travaillez ?' where id=19493;
update phrases set phrase_text='quel est le numéro de téléphone ?' where id=19494;
update phrases set phrase_text='quel est le prix de la chambre ?' where id=19495;
update phrases set phrase_text='ce est la température ?' where id=19496;
update phrases set phrase_text='qu’est-ce que c’est ça ?' where id=19497;
update phrases set phrase_text='ce est la date du jour ?' where id=19498;
update phrases set phrase_text='quoi de neuf ?' where id=19499;
update phrases set phrase_text='qu’est-ce qui ne va pas ?' where id=19500;
update phrases set phrase_text='quelle est votre adresse ?' where id=19501;
update phrases set phrase_text='ce est votre plat préféré ?' where id=19502;
update phrases set phrase_text='quel est votre film préféré ?' where id=19503;
update phrases set phrase_text='quel est votre nom ?' where id=19504;
update phrases set phrase_text='quel est votre nom ?' where id=19505;
update phrases set phrase_text='quelle est votre religion ?' where id=19506;
update phrases set phrase_text='quelle heure sont-ils arriver ?' where id=19507;
update phrases set phrase_text='quelle heure allez-vous à la station de bus ?' where id=19508;
update phrases set phrase_text='quelle heure avez-vous vous levez ?' where id=19509;
update phrases set phrase_text='quelle heure avez-vous d’aller dormir ?' where id=19510;
update phrases set phrase_text='quelle heure avez-vous vous réveillez ?' where id=19511;
update phrases set phrase_text='a quelle heure ça commence ?' where id=19512;
update phrases set phrase_text='a quelle heure le film débute-t-il ?' where id=19513;
update phrases set phrase_text='quelle heure le magasin ouvert ?' where id=19514;
update phrases set phrase_text='quelle heure allez-vous travailler tous les jours ?' where id=19515;
update phrases set phrase_text='quelle heure pensez-vous que vous aurez arrivez ?' where id=19516;
update phrases set phrase_text='quelle heure est la caisse ?' where id=19517;
update phrases set phrase_text='quelle heure est-il ?' where id=19518;
update phrases set phrase_text='quelle sera la météo demain ?' where id=19519;
update phrases set phrase_text='que voulez-vous boire ?' where id=19520;
update phrases set phrase_text='que voudriez-vous manger ?' where id=19521;
update phrases set phrase_text='où viennent-ils ?' where id=19522;
update phrases set phrase_text='quand reviendras-tu ?' where id=19523;
update phrases set phrase_text='quand allez-vous chercher votre ami ?' where id=19524;
update phrases set phrase_text='quand partez-vous ?' where id=19525;
update phrases set phrase_text='quand vous déménagez ?' where id=19526;
update phrases set phrase_text='quand est-ce arrivé ?' where id=19527;
update phrases set phrase_text='quand avez-vous arrivez à Boston ?' where id=19528;
update phrases set phrase_text='quand est-il arrivé ?' where id=19529;
update phrases set phrase_text='quand at-il arriver ?' where id=19530;
update phrases set phrase_text='quand at-il laissé ?' where id=19531;
update phrases set phrase_text='lorsque la banque ne ouvrir ?' where id=19532;
update phrases set phrase_text='lorsqu’il ne laisse le bus ?' where id=19533;
update phrases set phrase_text='lorsque l’avion ne arrive ?' where id=19534;
update phrases set phrase_text='quand avons-nous arrivons ?' where id=19535;
update phrases set phrase_text='quand pensez-vous arriver aux États-Unis ?' where id=19536;
update phrases set phrase_text='quand vous obtenez arrêt de travail ?' where id=19537;
update phrases set phrase_text='quand est le prochain bus à Philadelphie ?' where id=19538;
update phrases set phrase_text='c’est quand votre anniversaire ?' where id=19539;
update phrases set phrase_text='quand je suis allé au magasin, ils ne avaient pas de pommes ?' where id=19540;
update phrases set phrase_text='quand il sera prêt ?' where id=19541;
update phrases set phrase_text='quand souhaitez-vous rencontrer ?' where id=19542;
update phrases set phrase_text='où sont les t-shirts ?' where id=19543;
update phrases set phrase_text='où êtes-vous ?' where id=19544;
update phrases set phrase_text='d’où êtes-vous ?' where id=19545;
update phrases set phrase_text='où allez-vous ?' where id=19546;
update phrases set phrase_text='où allez-vous aller ?' where id=19547;
update phrases set phrase_text='Où puis-je acheter des billets ?' where id=19548;
update phrases set phrase_text='où puis-je échanger des dollars américains ?' where id=19549;
update phrases set phrase_text='où puis-je trouver un hôpital ?' where id=19550;
update phrases set phrase_text='où puis-je poster ce ?' where id=19551;
update phrases set phrase_text='Où puis-je louer une voiture ?' where id=19552;
update phrases set phrase_text='où est-ce arrivé ?' where id=19553;
update phrases set phrase_text='où êtes-vous allé ?' where id=19554;
update phrases set phrase_text='où avez-vous apprendre l’anglais ?' where id=19555;
update phrases set phrase_text='où avez-vous appris ?' where id=19556;
update phrases set phrase_text='où avez-vous dites ?' where id=19557;
update phrases set phrase_text='où avez-vous travaillé avant vous avez travaillé ici ?' where id=19558;
update phrases set phrase_text='où avez-vous mal ?' where id=19559;
update phrases set phrase_text='où ne fonctionne votre femme ?' where id=19560;
update phrases set phrase_text='où habitez-vous ?' where id=19561;
update phrases set phrase_text='où voulez-vous aller wantto ?' where id=19562;
update phrases set phrase_text='où travaillez-vous ?' where id=19563;
update phrases set phrase_text='où est-il ?' where id=19564;
update phrases set phrase_text='d’où est-il ?' where id=19565;
update phrases set phrase_text='où est-il ?' where id=19566;
update phrases set phrase_text='où est la rue principale ?' where id=19567;
update phrases set phrase_text='où est ma chemise ?' where id=19568;
update phrases set phrase_text='où est-elle ?' where id=19569;
update phrases set phrase_text='où est l’aéroport ?' where id=19570;
update phrases set phrase_text='où se trouvent les toilettes ?' where id=19571;
update phrases set phrase_text='où est la station de bus ?' where id=19572;
update phrases set phrase_text='où est-il un médecin qui parle anglais ?' where id=19573;
update phrases set phrase_text='où est-il un distributeur de billets ?' where id=19574;
update phrases set phrase_text='où est le restaurant le plus proche ?' where id=19575;
update phrases set phrase_text='où est la boîte aux lettres ?' where id=19576;
update phrases set phrase_text='où est l’hôpital le plus proche ?' where id=19577;
update phrases set phrase_text='où est la pharmacie ?' where id=19578;
update phrases set phrase_text='où est le bureau de poste ?' where id=19579;
update phrases set phrase_text='où étiez-vous ?' where id=19580;
update phrases set phrase_text='où voulez-vous aller ?' where id=19581;
update phrases set phrase_text='où aimeriez-vous rencontrer ?' where id=19582;
update phrases set phrase_text='ce qui est mieux ?' where id=19583;
update phrases set phrase_text='ce qui est mieux les spaghettis ou salade de poulet ?' where id=19584;
update phrases set phrase_text='Quel est le meilleur ?' where id=19585;
update phrases set phrase_text='laquelle ?' where id=19586;
update phrases set phrase_text='qui veux-tu ?' where id=19587;
update phrases set phrase_text='quel est le meilleur ?' where id=19588;
update phrases set phrase_text='lequel est le moins cher ?' where id=19589;
update phrases set phrase_text='lequel est le meilleur ?' where id=19590;
update phrases set phrase_text='quel chemin dois-je prendre ?' where id=19591;
update phrases set phrase_text='quelle école t-il allé ?' where id=19592;
update phrases set phrase_text='qui sont-ils ?' where id=19593;
update phrases set phrase_text='qu’est-ce ?' where id=19594;
update phrases set phrase_text='qui est-ce ?' where id=19595;
update phrases set phrase_text='qui est livre est cela ?' where id=19596;
update phrases set phrase_text='qui a envoyé cette lettre ?' where id=19597;
update phrases set phrase_text='qui est cet homme là-bas ?' where id=19598;
update phrases set phrase_text='qui vous a enseigné ?' where id=19599;
update phrases set phrase_text='qui vous a enseigné que ?' where id=19600;
update phrases set phrase_text='Qui était-ce ?' where id=19601;
update phrases set phrase_text='qui était votre professeur ?' where id=19602;
update phrases set phrase_text='qui a gagné ?' where id=19603;
update phrases set phrase_text='à qui voulez-vous parler ?' where id=19604;
update phrases set phrase_text='pourquoi arent allez-vous ?' where id=19605;
update phrases set phrase_text='pourquoi riez-vous ?' where id=19606;
update phrases set phrase_text='pourquoi avez-vous fait cela ?' where id=19607;
update phrases set phrase_text='pourquoi avez-vous fait dire ça ?' where id=19608;
update phrases set phrase_text='pourquoi pas ?' where id=19609;
update phrases set phrase_text='allez-vous me appeler un taxi s’il vous plaît ?' where id=19610;
update phrases set phrase_text='allez-vous me donner une serviette s’il vous plaît ?' where id=19611;
update phrases set phrase_text='allez-vous me passer le sel s’il vous plaît ?' where id=19612;
update phrases set phrase_text='allez-vous mettre cela dans la voiture pour moi ?' where id=19613;
update phrases set phrase_text='allez-vous me rappeler ?' where id=19614;
update phrases set phrase_text='allez-vous me ramener chez moi ?' where id=19615;
update phrases set phrase_text='voulez-vous lui demander de me rappeler s’il vous plaît ?' where id=19616;
update phrases set phrase_text='voulez-vous lui demander de venir ici ?' where id=19617;
update phrases set phrase_text='voulez-vous un verre d’eau ?' where id=19618;
update phrases set phrase_text='voulez-vous café ou de thé ?' where id=19619;
update phrases set phrase_text='voulez-vous boire quelque chose ?' where id=19620;
update phrases set phrase_text='voulez-vous quelque chose à manger ?' where id=19621;
update phrases set phrase_text='voulez-vous un peu d’eau ?' where id=19622;
update phrases set phrase_text='voulez-vous un peu de vin ?' where id=19623;
update phrases set phrase_text='voulez-vous buythis ?' where id=19624;
update phrases set phrase_text='voulez-vous faire une promenade ?' where id=19625;
update phrases set phrase_text='voulez-vous dîner avec moi ?' where id=19626;
update phrases set phrase_text='souhaitez-vous louer un film ?' where id=19627;
update phrases set phrase_text='voulez-vous regarder TV ?' where id=19628;
update phrases set phrase_text='voulez-vous de l’eau ou du lait ?' where id=19629;
update phrases set phrase_text='prendriez-vous un message s’il vous plaît ?' where id=19630;
update phrases set phrase_text='oui' where id=19631;
update phrases set phrase_text='oui vraiment' where id=19632;
update phrases set phrase_text='vous avez une très belle voiture' where id=19633;
update phrases set phrase_text='Tu es superbe' where id=19634;
update phrases set phrase_text='vous ressemblez à ma sœur' where id=19635;
update phrases set phrase_text='vous regardez fatigué' where id=19636;
update phrases set phrase_text='vos enfants sont très bien comportés' where id=19637;
update phrases set phrase_text='votre fille' where id=19638;
update phrases set phrase_text='tu es belle' where id=19639;
update phrases set phrase_text='vous avez raison' where id=19640;
update phrases set phrase_text='vous êtes plus intelligent que lui' where id=19641;
update phrases set phrase_text='vous êtes très agréable' where id=19642;
update phrases set phrase_text='vous êtes très intelligent' where id=19643;
update phrases set phrase_text='soyez le bienvenu' where id=19644;
update phrases set phrase_text='votre maison est très agréable' where id=19645;
update phrases set phrase_text='vos choses sont tous là' where id=19646;
update phrases set phrase_text='vous parlez très bien anglais' where id=19647;
